### ISSUE TITLE
how to turn off a feature from node.js redis?

### ISSUE THREAD

**Issue by pcompassion** [jazzband/django-constance#101]
I'd like to turn off a feature (by unsetting a constance value in redis)

I'm doing it from node.js. 

It seems constance uses python pickle's dump to store truth value.  
Isn't the dumped value supposed to change as pickle changes with python version?

How should I toggle truth values from outside of python world?

I'm setting `I00\n.` for False value. Does this look ok?

**Comment by jezdez** [comment]
This isn't supported, sorry.

**Comment by Mogost** [comment]
This is still a problem for django-constance. Trying to resolve it in linked PR
