### ISSUE TITLE
Change max length for key field in model Constance

### ISSUE THREAD

**Issue by falknes** [jazzband/django-constance#121]
Would it be possible to change max_length of key in Constance database model from 255 to a value usable with encoding ``utfmb8``?

From:
```python
key = models.CharField(max_length=255, unique=True)
```

To for example:
```python
key = models.CharField(max_length=150, unique=True)
```

Having a key thats 255 characters long feels like overkill, and changing it to a smaler value will also make it usable by in mysql without enabling "innodb_large_prefix" when using true utf8 support.

The current setup with 255 characters allows keys to be:
```
Lorem_ipsum_dolor_sit_amet__consectetur_adipiscing_elit__Cras_consectetur_duinon_feugiat_finibus__Aliquam_sit_amet_mauris_id_tortor_rhoncus_gravida_eu_eu_augue__Nullam_ante_turpis__convallis_in_nisl_et__iaculis_luctus_magna_aSed_a_rutrum_massae_Sed_amete
```

``utf8mb4`` max at the moment is 191 characters with regular max key length of 767

**Comment by michaelkuty** [comment]
I think that you could override this model if you want this type of change..

**Comment by camilonova** [comment]
Agree.

**Comment by athre0z** [comment]
I think this should be reconsidered. `utf8mb4` is required to properly store Emojis and, given the popularity of those, will probably sooner or later become the standard charset for most web-apps.

**Comment by camilonova** [comment]
@jezdez What do you think?

**Comment by athre0z** [comment]
An easy way to not break compatibility for people with ultra-long keys could be to just make the key length configurable, just like e.g. the social auth Django app does:
https://github.com/python-social-auth/social-app-django/blob/master/social_django/models.py#L17
https://github.com/python-social-auth/social-app-django/blob/master/social_django/migrations/0001_initial.py#L13

**Comment by jezdez** [comment]
While utf8mb4 is required for MySQL/MariaDB servers to store the full UTF-8 character sets I don't see how this is useful for constance. Using Emoji or other characters covered by utf8mb4 are hardly useful for configuration variable names. In other words, this is an extreme edge case and a required data migration to support it is way out of scope of constance.

If you still want to use utf8mb4 in your app for other models, feel free to use it when instantiating the database and then change the collation of the `constance_config` table back to the default (utf8_generic_ci or similar, but check your database documentation for which it is).

Making the database model pluggable is **not** an alternative given the increased implementation and operational complexity.
