### ISSUE TITLE
ImportError: cannot import name caches

### ISSUE THREAD

**Issue by ax003d** [jazzband/django-constance#124]
I installed django-constance from pip, and the version is django_constance-1.1.1
I used with database backend.
When I started my application, it shows:

        app = import_module(appname)
      File "/mnt/env-gizwits/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
        __import__(name)
      File "/mnt/env-gizwits/local/lib/python2.7/site-packages/constance/backends/database/__init__.py", line 1, in <module>
        from django.core.cache import caches
    ImportError: cannot import name caches

I searched the django document, the example there is

    >>> from django.core.cache import cache

Is it a typo problem?

**Comment by pacahon** [comment]
Too late I guess, but `django.core.cache.caches` is a new feature of Django 1.7
https://docs.djangoproject.com/en/1.8/topics/cache/#accessing-the-cache

**Comment by ax003d** [comment]
OK, I see. So database backend feature is compatible with Django > 1.7?

**Comment by pacahon** [comment]
Hello, @ax003d. It's incompatible with Django > 1.6 since version 1.1 http://django-constance.readthedocs.org/en/latest/changes.html#v1-1-2015-09-24

**Comment by ax003d** [comment]
Thank you!
