### ISSUE TITLE
Support list or dict settings

### ISSUE THREAD

**Issue by ax003d** [jazzband/django-constance#125]
There are some configs in my settings which are list or dict.
Does django-contance has any plan to support list or dict?

**Comment by pacahon** [comment]
I'm not a contributor, but I think it's too complicated. 
python `list` can contains `str`, `int` or another `list`/`dict`. Structure can be nested and nobody knows how to display this hell.
You can use `ADDITIONAL_FIELDS` setting to add your own implementation.

**Comment by michaelkuty** [comment]
Please see new feature - custom types, which alows custom field types with widget, you can defined whatever you want https://github.com/jazzband/django-constance/commit/803cf465c7cffc1a2c36a1a89abbba14964c57f0
