### ISSUE TITLE
Using database backend, but throws exception backend Redis

### ISSUE THREAD

**Issue by valbertovc** [jazzband/django-constance#128]
I installed ```pip install django-constance[database]``` and configured my settings.py but when I run the command Django ```$ ./manage.py runserver ```shows this exception.

comand line output:
> Django.core.exceptions.ImproperlyConfigured: The Redis backend pens-py requires to be installed.

My settings.py:
```
INSTALLED_APPS = (
     [...]
     'constance',
     'constance.backends.database',
)

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

TEMPLATES = [
     {
         'BACKEND' 'django.template.backends.django.DjangoTemplates'
         'SRD': [os.path.join (BASE_DIR, 'templates')]
         'APP_DIRS': True,
         'OPTIONS': {
             'context_processors': [
                 ...
                 'constance.context_processors.config'
             ]
         },
     },
]
```

The Constance should not ignore the Redis since I configured for the database backend?
It worked when I commented all references to the constance plugin and ran the ```$ ./manage.py migrate database```

**Comment by camilonova** [comment]
As far as I remember we don't require ```pens-py``` are you sure the problem is not related with another package you are using?
