### ISSUE TITLE
I want dynamic config keys

### ISSUE THREAD

**Issue by craynic** [jazzband/django-constance#139]
Could it be possible to provide a setting to make dynamic config keys? That is, I can get and set config without checking if is in CONSTANCE_CONFIG.
In my case, I want to have constance settings for many environments, which I cannot determine in django settings.
Seems it's not complex in code.

**Comment by camilonova** [comment]
I'll recommend you to use a custom implementation on your project.

This seems is out of the purpose of django-constance.
