### ISSUE TITLE
constance and files/images

### ISSUE THREAD

**Issue by sobolevn** [jazzband/django-constance#141]
Hi, thanks for awesome project! I have faced a trouble getting to work you app with `ImageField`. Also, I didn't find any documentation hints about it. So I don't know if that's possible.

Here's what happens:

0. I have used you app for my settings, but it was floats and strings (no problems here)
1. Now I have made the following setup:

```
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {}]
}

CONSTANCE_CONFIG = {
    # Works:
    'THE_ANSWER': (42, 'Answer to the Ultimate Question of Life, '
                       'The Universe, and Everything', float),
    # Does not work:
    'WATERMARK_IMAGE': ('default.png', 'Default image to add on thumbnails', 'image_field')
}
```

2. When I enter my admin page, it looks like the following:
<img width="1233" alt="2016-05-22 0 35 46" src="https://cloud.githubusercontent.com/assets/4660275/15453346/1ecc4aca-201b-11e6-913e-947de3158660.png">
3. I can choose the file to be uploaded, but it is not saved:
<img width="1213" alt="2016-05-22 12 45 15" src="https://cloud.githubusercontent.com/assets/4660275/15453349/351b95ce-201b-11e6-93bd-309184c115a0.png">
4. Here's the result:
<img width="1211" alt="2016-05-22 12 45 38" src="https://cloud.githubusercontent.com/assets/4660275/15453347/307a96be-201b-11e6-89bf-9f82afde276a.png">

Any ideas to guide me?

**Comment by camilonova** [comment]
The admin html form have the *enctype* attribute?

**Comment by sobolevn** [comment]
No, it does not. 
<img width="808" alt="2016-05-24 23 39 38" src="https://cloud.githubusercontent.com/assets/4660275/15519178/dca4afb2-2208-11e6-91b4-51d434a55212.png">

**Comment by camilonova** [comment]
@sobolevn Please try again installing the package from github.

**Comment by MCopperhead** [comment]
@sobolevn 
Hi. It is still not working. There are no request.FILES passed to the form at **changelist_view**:
`form = self.change_list_form(data=request.POST, initial=initial)`

I've added files to the form, like this: 
`form = self.change_list_form(data=request.POST, files=request.FILES, initial=initial)`
but it gives me an error upon save: **'NoneType' object has no attribute 'read'**

Could you help me with that, please?

**Comment by sobolevn** [comment]
@MCopperhead I have not tried this new feature yet.

@camilonova what do you think?

**Comment by camilonova** [comment]
@MCopperhead @sobolevn Please try this https://github.com/jazzband/django-constance/pull/242
