### ISSUE TITLE
Is there a way to localize constants?

### ISSUE THREAD

**Issue by programmdesign** [jazzband/django-constance#142]
Hi. I was wondering if there's a way to localize my constant values? For example, I'd like to store email subjects or city names with django-constance which I want to  be translated depending on the language I'm using in my django app. However, if I use django's translation object (_('...')) on the default values, I'm getting an error, saying that these 'proxy' objects are not supported by django-constance. Is there any workaround to this? Thanks!

```
# This setting won't work ... 
CONSTANCE_CONFIG = {
    'SUBJECT_PURCHASE_REQUEST_RECEIVED_SELLER': (_(u'New purchase request (#{transaction_id})'), _(u'Email subject: purchase request received by seller')),
}
```

**Comment by camilonova** [comment]
Are you using ugettext_lazy ?
