### ISSUE TITLE
Tests not running for database backend

### ISSUE THREAD

**Issue by prokaktus** [jazzband/django-constance#144]
Hi!

I tried to run tests with html report from coverage -- and this is what I've got:

![Tests not running for backend](https://cloud.githubusercontent.com/assets/193254/15801441/673c0cf0-2a9d-11e6-9c3a-e364c829ed39.png)

As I can understand, `test_database.py` not running correctly and run tests on `redisd` backend (I've put debug output into `test_database.py`).

This is not local problem, because travis `coverage report` also confirm that `database/__init__.py` doesn't have correctly testing:
![py34-django-18 output](https://cloud.githubusercontent.com/assets/193254/15801454/f6cac0d2-2a9d-11e6-9499-a4fb06f08361.png)

**Comment by camilonova** [comment]
Can you elaborate a fix?

**Comment by prokaktus** [comment]
@camilonova thanks for the answer! I'll try to provide fix.

**Comment by camilonova** [comment]
@prokaktus Thank you.
