### ISSUE TITLE
'Meta' object has no attribute 'app_config'

### ISSUE THREAD

**Issue by zruu** [jazzband/django-constance#148]
I'm getting the error: 'Meta' object has no attribute 'app_config' when trying to access /admin 

Mezzanine 4.1.0
Django 1.9.6
Python 3.4.4
MySQL 5.7.10
Darwin 15.5.0

**Comment by camilonova** [comment]
Which version of django-constance?

**Comment by zruu** [comment]
The latest version (1.2)

**Comment by stephenmcd** [comment]
See the linked issue in Mezzanine for more detail. Basically it appears that constance registers a fake model class, with a fake meta class, against an admin class, which doesn't conform to the same members as django.db.models.options.Options.

**Comment by camilonova** [comment]
Cool. Thanks.

**Comment by camilonova** [comment]
Any ideas?
