### ISSUE TITLE
Overridding of Constance values in unit tests not working when using CONSTANCE_DATABASE_CACHE_BACKEND

### ISSUE THREAD

**Issue by morlandi** [jazzband/django-constance#151]
### Test settings

```
# add MY_FLAG to CONSTANCE_CONFIG  
CONSTANCE_CONFIG['MY_FLAG'] = (True, 'a test flag')
```
### Sample unit test

```
import django
from django.test import override_settings
from constance import config
from constance.test import override_config

class ConstanceTestCase(django.test.TransactionTestCase):

    def test_1(self):
        self.assertTrue(config.MY_FLAG)

    @override_config(MY_FLAG=True)
    def test_2(self):
        self.assertTrue(config.MY_FLAG)

    @override_settings(CONSTANCE_DATABASE_CACHE_BACKEND=None)
    @override_config(MY_FLAG=False)
    def test_3(self):
        self.assertFalse(config.MY_FLAG)

    @override_settings(CONSTANCE_DATABASE_CACHE_BACKEND='default')
    @override_config(MY_FLAG=False)
    def test_4(self):
        self.assertFalse(config.MY_FLAG)
```
### The problem

test_3() and test_4() fail when settings.py enables the caching of constance values:

```
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/0'
    },
}

CONSTANCE_DATABASE_CACHE_BACKEND = 'default'
```

 @override_settings(CONSTANCE_DATABASE_CACHE_BACKEND=None) doesn't seem to help in the unit test, while removing CONSTANCE_DATABASE_CACHE_BACKEND from settings solves the problem
### System configuration
- Django version: 1.8.6
- Python version: 2.7.10
- django-constance version: django-constance[database]==1.2

**Comment by rev112** [comment]
It looks like overriding in tests works properly in the current version (1.3.4). Could someone confirm, please?

**Comment by morlandi** [comment]
Yes, it does.
Thank you

**Comment by bmwant** [comment]
I'm using dummy constance backend when running tests, so it does not able to store anything in cache

```
from constance.backends import Backend

class DummyBackend(Backend):
    def get(self, key):
        pass

    def set(self, key, value):
        pass

    def mget(self, keys):
        pass

```

and in test setting provide

```
CONSTANCE_BACKEND = 'tests.utils.DummyBackend'
```

or whatever path to the module where you define this dummy backend

**Comment by morlandi** [comment]
Very useful, @bmwant 

However, when you need to alter some settings in the unit test, something like:

    config.SOMETHING = somevalue

a better choice in your test settings could be:

    CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

**Comment by fabiocaccamo** [comment]
@morlandi I understand, so I think that an `override_setting` is what you would need, right?
