### ISSUE TITLE
Need ordering in the form

### ISSUE THREAD

**Issue by iamkhush** [jazzband/django-constance#153]
Currently configuration items are ordered on basis of name  -

`context['config_values'].sort(key=itemgetter('name'))`

Need custom ordering somehow, instead of completely rewriting the `changelist_view` method

**Comment by camilonova** [comment]
Sounds like a good idea, please elaborate a PR so we can review the changes.

**Comment by iamkhush** [comment]
Sent a PR - https://github.com/jazzband/django-constance/pull/157 .

**Comment by camilonova** [comment]
PR was merged. Thanks.
