### ISSUE TITLE
picklefield breaks Django 1.10 compat

### ISSUE THREAD

**Issue by pySilver** [jazzband/django-constance#156]
picklefield is not django 1.10 compatible and it looks like dead... so it'd would be nice to drop it or take that few lines inside constance.

**Comment by camilonova** [comment]
@pySilver Would you like to elaborate a PR on it?

**Comment by felixxm** [comment]
[django-picklefield](https://github.com/gintas/django-picklefield) is Django 1.9-1.10 compatible. Check my last [PR](https://github.com/gintas/django-picklefield/pull/20) and CI [results](https://travis-ci.org/gintas/django-picklefield/builds/165633435). This issue should be closed, unless you find any bug in picklefield, if so create issue in django-picklefield. I will try to fix it.

**Comment by camilonova** [comment]
Thank you.
