### ISSUE TITLE
provide signal sending on "save"

### ISSUE THREAD

**Issue by lklabs** [jazzband/django-constance#158]
### Describe the problem

**Feature request:**
Please provide signal sending on "save" (similar to post_save in django models) so user app could catch it and perform some actions with just updated settings

### Steps to reproduce

N/A

### System configuration

* Django version: 1.10
* Python version: 2.7

**Comment by camilonova** [comment]
Done. http://django-constance.readthedocs.io/en/latest/#signals

**Comment by jezdez** [comment]
Reopening this issue following my comments in 94fabdf7c300d3d164d25e7db1b60c77612c943c. For the record, I feel like this feature was hurried and didn't go through the necessary code review, not even a PR was opened.

**Comment by camilonova** [comment]
@jezdez Got it, I'll open a PR.

**Comment by benwhalley** [comment]
One thing I've come across is that this new signal doesn't provide a `raw` kwarg, as does Django's post-save signal. This means it's impossible to detect when constance is loading from a fixture. Would it be possible to mimic the 'raw' argument?

**Comment by jezdez** [comment]
@benwhalley I'm not sure how we could determine if the constance value is set from a fixture if what actually happens during fixture loading is just adding the database entry and circumventing the constance config API which would trigger the `config_updated` signal. Definitely open a separate ticket so we can keep track of this. 

As a work-around for now I think it may make sense to use tools like [django-seed](https://github.com/brobin/django-seed) for setting up the constance fixtures and use the constance config API directly. That way it would go through the proper API and the signal would be triggered.
