### ISSUE TITLE
1.3.2 is broken

### ISSUE THREAD

**Issue by jezdez** [jazzband/django-constance#161]
Commit https://github.com/jazzband/django-constance/commit/56fb550044f004805429f0e70bd3e92ce55845af tried to fix an issue that didn't have an issue or PR opened.

[Automatic tests failed](https://travis-ci.org/jazzband/django-constance/builds/160720592) and yet a PyPI release was done.

This needs to be solved properly.

**Comment by camilonova** [comment]
@jezdez I'm very sorry about that. I did open #162 to get some help with travis.
