### ISSUE TITLE
Incorect ordering for config. Don't work ordered dict

### ISSUE THREAD

**Issue by Lumax-Rus** [jazzband/django-constance#167]
### Describe the problem
Don't work ordered dict.
Incorect line https://github.com/jazzband/django-constance/blob/master/constance/admin.py#L217

### Steps to reproduce

`CONSTANCE_CONFIG = OrderedDict([
   ('second', ('Second', 'Second')),
   ('first', ('first', 'first')),
])`

### System configuration

* Django version: 1.9
* Python version: 2.7

**Comment by Lumax-Rus** [comment]
https://github.com/jazzband/django-constance/pull/166

**Comment by camilonova** [comment]
Fixed on #166
