### ISSUE TITLE
"Reset to Default" button in Django Admin

### ISSUE THREAD

**Issue by rvernica** [jazzband/django-constance#178]
### Feature Request

This is a feature request. In the *Django Admin*, on the *Constance config* page, for each value, we could have a "Reset to Default" button. 

Right now, one could reset a value to default by Copy & Paste from the *DEFAULT* to the *VALUE* field but this is error prone.

**Comment by camilonova** [comment]
I like it. Could you work on it?

**Comment by jezdez** [comment]
Let's use checkboxes in front of the values like the Django admin actions -- a button for each value is a UI disaster

**Comment by rvernica** [comment]
I agree that a button for each value is a UI disaster.

Here is how I would do it. I would add a *Reset to Default* link (`<a href=...`) after each value. When the link is clicked, JavaScript intercepts the event and copies the value from the *Default* column into the field from *Value* column. Next, the user can continue editing the value and click *Save* to save it. Just clicking *Reset to Default* without clicking *Save* won't persist anything.

So, the feature would be completely client side and easy to implement.

**Comment by camilonova** [comment]
Sounds good to me

**Comment by jezdez** [comment]
Yep, to me too, let's try to prevent using a JavaScript framework for this though and stick to vanilla JavaScript instead to reduce the maintenance burden. In terms of browser support I think it's fair to say that we should support all the browsers supported by the Django admin.

**Comment by rvernica** [comment]
See #183 for a PR adding this feature.
