### ISSUE TITLE
i18n in settings

### ISSUE THREAD

**Issue by adrienbrunet** [jazzband/django-constance#182]
### Describe the problem
How can we provide settings with i18n?

```python
CONSTANCE_CONFIG = {
    'FOO': (
        "bar",
        'my usefull help text',
}
```

Can we easily provide translation for the key, value and help text strings?

Thanks!

**Comment by jezdez** [comment]
Using `ugettext_lazy` for the help text should work, can you try?

Key and value are non-translatable, or at least they weren't designed for that purpose. But even if the translation of those works, translating the key wouldn't make any sense since it's referred to in code as `config.FOO` so needs to be a specific string.

**Comment by adrienbrunet** [comment]
I'm well aware of `ugettext_lazy` =).

I have some configuration I need to make available. I'd like to avoid to create a model with a few fields (attr1, attr2, attr3) and use [modeltranslation](https://github.com/deschler/django-modeltranslation) for i18n. I don't like to have one instance from a model, it seems overkill.

I thought django-constance would do the trick. And it does very well until you want translations.

I need to make available some atttributes which could lay in settings but I need them to be editable.

I get that the key should stay yhe same but as it is displayed as a label, I'd like it to be translated. The default value and the help_text could be translated but I'd love to allow user to specify translations directly like modeltranslation allow.

As far as you're concern, I think we can close the issue. The library just does fit my needs. :(
