### ISSUE TITLE
Possibility to write initial default values to database?

### ISSUE THREAD

**Issue by michaelonken** [jazzband/django-constance#184]
In my project I'm using the django and additional constance configuration settings in the (SQL) database from other programming languages, too, namely C++. The problem is that default values (as I understand) are not written to the SQL database but instead are provided by constance from the configuration file at runtime.

Is there an easy way to write initial default values also to the database?

**Comment by camilonova** [comment]
You can use a data migration and the database backend.

**Comment by jezdez** [comment]
This isn't supported out of the box, but here's a snippet for this edge case:

```python
from constance import config

for name in dir(config):
    setattr(config, name, getattr(config, name))
```

This will write the config values to the backend by force and should only be used in the edge case described above.

**Comment by michaelonken** [comment]
Great, thanks!
