### ISSUE TITLE
manage.py set does not work for DateTime

### ISSUE THREAD

**Issue by rvernica** [jazzband/django-constance#186]
### Describe the problem

Setting values using `manage.py` commands does not work for `DateTime` type.

### Steps to reproduce

`settings.py`:
```
CONSTANCE_CONFIG = {
    'foo': (datetime.datetime(1972, 11, 30, 1, 10, 0), 'help text'),
}
```
```
$ python manage.py constance list
foo	1972-11-30 01:10:00
$ python manage.py constance set foo '1972-11-30 01:10:00'
CommandError: Enter a list of values.
```
The `value` passed to `manage.py` first goes through `field.to_python` and then errors in `field.clean`, see [line 25](https://github.com/jazzband/django-constance/blob/8db90e808756f62941c025c6dc522156d7271db0/constance/management/commands/constance.py#L25). In the Django source tree (version `1.10.4`), `to_python` does not do anything, see [line 130](https://github.com/django/django/blob/1.10.4/django/forms/fields.py#L130), while `clean` is checking if `value` is a `list` or a `tuple`, see [line 1015](https://github.com/django/django/blob/1.10.4/django/forms/fields.py#L1015). Since `value` is just a string, this code can't possibly work.

### System configuration

* Constance revision: 8db90e808756f62941c025c6dc522156d7271db0
* Django version: `1.10.4`
* Python version: `2.7.12`

**Comment by therefromhere** [comment]
I'm thinking to handle MultiValueField's (like SplitDateTimeField) in a generic way, the set command could consume all following parameters.

This does mean that the command line interface is affected by the admin ui (ie if you changed the field to use DateTimeField instead, the command line syntax would need to change), but it seems like the least-bad option?
