### ISSUE TITLE
"Reset to default" not working on boolean widget

### ISSUE THREAD

**Issue by therefromhere** [jazzband/django-constance#189]
### Describe the problem

The reset to default link isn't working for checkboxes

Because the generated JS is:

`document.getElementById('id_MY_BOOLEAN').value = 'True'; return false;`

There's 2 issues here:  

* stringified python `'True'` instead of JS bool `true`
* Checkboxes don't have a `.value`, they used `.checked`

This would work:

`document.getElementById('id_MY_BOOLEAN').checked = true; return false;`

### Steps to reproduce

Add a boolean Constance value.

### System configuration

* Django version: 1.8.17
* Python version: 2.7.12

**Comment by rvernica** [comment]
Fixed in PR #191
