### ISSUE TITLE
track the history of config changes

### ISSUE THREAD

**Issue by dineshkumardg** [jazzband/django-constance#19]
Can you add a privilege to track the previous config changes???

**Comment by aleszoulek** [comment]
Not sure if that should be in scope of the project. Maybe custom backend, that would be db-only and keeping that history?
Constance itself could just log the changes over python logging, so the user can monitor those in his logging system. (?)

**Comment by MarZab** [comment]
Is there a specific reason `django_admin_log` can not be used?

**Comment by camilonova** [comment]
Well, seems a good time to close this issue. I agree is not in the scope of the project.
