### ISSUE TITLE
False actually is not False in CONSTANCE_ADDITIONAL_FIELDS

### ISSUE THREAD

**Issue by xidui** [jazzband/django-constance#199]
### Describe the problem
this is my config
```python
CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_null_check': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((True, 'yes'), (False, 'no'))
    }],
}
CONSTANCE_CONFIG = {
    'ENABLE_DATABASE_HEARTBEAT': (False, 'select yes or no', 'yes_no_null_check'),  # NOQA
}
```
But after I get the config
```python
from constance import config
print type(config.ENABLE_DATABASE_HEARTBEAT)
```

It said that it was of `unicode` type, not bool.

### System configuration

* Django version: 1.10.0
* Python version: 2.7

**Comment by SebCorbin** [comment]
This issue is due to `ChoiceField`,  that will simply save the value from the form. During the rendering, `True` is displayed as `'True'` in the `<option>` value. To get around that, use `TypedChoiceField` with `coerce=lambda v: v == 'True'`.
