### ISSUE TITLE
adding password validators to constance?

### ISSUE THREAD

**Issue by Etiennepi** [jazzband/django-constance#202]
### I need to add the django password validators to constance

I have a lab at school that requires me to be able to modify the password validators dynamically.
Unfortunately, constance doesn't handle dictionaries as config values

### Steps to reproduce

Attempt to place a dictionary as a constance config

### System configuration

* Django version: 1.10
* Python version: 3.4, 3.5 (attempted on both)

**Comment by camilonova** [comment]
Seems we don't support dictionaries at this time. Feel free to work on a PR if you want to do so.
