### ISSUE TITLE
Default values should use select keys

### ISSUE THREAD

**Issue by aarcro** [jazzband/django-constance#221]
### Describe the problem

As a django admin user
I want to see the default value of a select shown as the label
So I am not confused by database values

Currently you cannot set the default with the label, as that's an invalid value.
And setting it to the db value is confusing to the end user.

### Steps to reproduce

```python
CONSTANCE_ADDITIONAL_FIELDS = {
    'fancy_sort_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (('-like_count', 'Popular'), ('created_datetime', 'Recent'))
    }],
}

# This doesn't work, Exception for "Popular is not a valid field"
CONSTANCE_CONFIG = {
    'FANCY_SORT_BY': ('Popular', 'select sorting of selfies', 'fancy_sort_select'),
}

# This works, but displays '-like_count' as the default
# which the user won't understand as it is not an option in the dropdown
CONSTANCE_CONFIG = {
    'FANCY_SORT_BY': ('-like_count', 'select sorting of selfies', 'fancy_sort_select'),
}
```

### System configuration

* Django version: 1.11
* Python version: 3.6

**Comment by jezdez** [comment]
Sorry but this is out of scope of this app.

**Comment by aarcro** [comment]
I really think it is in scope. You give this example in the documentation:

```
CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_null_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((None, "-----"), ("yes", "Yes"), ("no", "No"))
    }],
}

CONSTANCE_CONFIG = {
    'MY_SELECT_KEY': ('yes', 'select yes or no', 'yes_no_null_select'),
}
```

And it really breaks down when the database value differs from the select display choices by more than the capitalization.

The default for a field like this should be specified with the display option, so the user sees "Yes" (rather than "yes") next to a choice for "Yes" or "No".

Consider choice that are an enum: ` 'choices': ((None, "-----"), (1, "Yes"), (2, "No"))`

You'll show the user a default of 1, which has no obvious correlation to the Yes/No select widget presented. What ever the field class is, it should be used to translate the default value.
