### ISSUE TITLE
permission 'change_config' name can't be changed

### ISSUE THREAD

**Issue by yinkanghong** [jazzband/django-constance#223]
### permission 'change_config' name can't be changed

when `migrate` i get a permission name `Can change config` and codename of this permission is `change_config` ,if i change the name of this permission,next time i `migrate` will get error like `django.db.utils.IntegrityError: (1062, "Duplicate entry '2-change_config' for key 'auth_permission_content_type_id_codename_01ab37
5a_uniq'")
`

### Steps to reproduce

review the code,i have find you have write `            permission, created = Permission.objects.using(using).get_or_create(
                name='Can change config',
                content_type=content_type,
                codename='change_config')` in constance/app.py line29, i wish your can change it to

`            permission, created = Permission.objects.using(using).get_or_create(
                content_type=content_type,
                codename='change_config')`
`            if created:`
`                permission.name = 'Can change config'`
`                permission.save()`（really don't know how to add code block）
to allow user custom permission name,thank you.
### System configuration

* Django version:1.11.1
* Python version:3.6

**Comment by jezdez** [comment]
Changing a permission name is not something that is advisable and AFAIK not supported by Django. So in other words: don't change the permission name.
