### ISSUE TITLE
Change Config verbose_name

### ISSUE THREAD

**Issue by jundymek** [jazzband/django-constance#226]
### Describe the problem

Is it possible to override Config meta class and change 'Config' to 'My text'?
There is a link to my stackoverflow question: https://stackoverflow.com/questions/44914601/django-change-app-name-in-admin

### System configuration

* Django version: 1.10.5
* Python version: 3.5.2

**Comment by jezdez** [comment]
This was just answered fully in https://github.com/jazzband/django-constance/issues/102#issuecomment-346276637.
