### ISSUE TITLE
Missing info for 'version' field in docs for custom form

### ISSUE THREAD

**Issue by not-much-io** [jazzband/django-constance#228]
The guide here fails to mention the need to include a "version" field in your custom form for it to work: https://django-constance.readthedocs.io/en/latest/index.html#custom-settings-form

An explanation on how to handle it properly would also be welcome.

```
class CustomForm(ConstanceForm):
    def __init__(self, *args, **kwargs):
        super(CustomForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'FIELD1',
            'FIELD2',
            'version',  # Without this field, form will fail silently
        )
        self.helper.form_action = '.'
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Save'))
```

To reproduce simply make a custom form with all the fields defined in settings.py, it won't work. Add a 'version' field and it should work.

The invisible error can be seen in self.errors of CustomForm. (For example in clean()) 

### System configuration

* Django version: 1.10.7
* Python version: 3.5.2

**Comment by camilonova** [comment]
Could you please make a PR updating the documentation?

**Comment by not-much-io** [comment]
I could yes, but I don't really understand what are we supposed to do with the version field?

Just include it without any special handling?

**Comment by camilonova** [comment]
Version field is used to track if there was any change in a constance setting from other place.

You should see in action when editing constance in a different tab and try to save it.
