### ISSUE TITLE
Bad effects on python2 to python3 migration....

### ISSUE THREAD

**Issue by gb119** [jazzband/django-constance#232]
### Describe the problem

This is probably a bit of a corner case, but I recently migrated a Django codebase from Python 2.7 to 3.6 and hit a problem with DateTime values stored in a constance database backed. The issue is that the pickled data was not unpickling properly and the underlying django-picklefield was returning the raw string object if the unpickle failed.

It seems that it is simply really hard to get a DateTime pickled in 2.7 to unpickle nicely in 3.6, but this is the sort of thing I can live with. The unfortunate bit is that constance doesn't seem to have a guard for picklefield returning the raw string and that crashes the Admin pages (it also crashed my app, but that's my problem!) - it probably shouldn't do that.... A better behaviour would be to put up a warning on the Admin pages to the effect that there is possible data corruption.

There is a work-around by using the constance command line interface to set the constants back to a valid datetime (it would be even nicer to have a 'reset' in the command interface to simple reset them to the default values) and the admin pages could be loaded again.

### Steps to reproduce

Setup constance to store some DateTime data whilst running a Python 2.7 codebase.
Upgrade to Python 3.x
Try to use the constance admin pages to look at the constance variables

### System configuration

* Django version: 1.11.1
* Python version: from 2.7.11 switching to 3.6.2

**Comment by jezdez** [comment]
You're right, this sounds like a problem, but I'm afraid, solving this is outside the scope of this app. There *is* a reset link nowadays in the admin, so maybe that suffices as a work around at least.
