### ISSUE TITLE
Whats The Correct Way to do a Migration

### ISSUE THREAD

**Issue by fission6** [jazzband/django-constance#234]
Whats the correct way / advised way to do a migration to put in a new value for a django-constance setting? I see there is a management command but should the approach be to do a migration in the classical sense using the direct constance models?

Use case
I have a setting: 'max_value' = 30, i then change it to 40 via admin

I now want max_value to be 50 as the standard setting, I should change this in settings.py BUT do I need a migration too?

**Comment by jezdez** [comment]
@fission6 The setting is always going to be the default of the config value. So if you've changed it via the admin already, changing the default won't automatically update the overridden value. For that you should use a [Django data migration](https://docs.djangoproject.com/en/1.11/topics/migrations/#data-migrations).
