### ISSUE TITLE
How to get the setting's values inside django model

### ISSUE THREAD

**Issue by junejie** [jazzband/django-constance#235]
### Describe the problem
I want to get the value of configuration inside the django models

Tell us about the problem you're having
I can get the configuration values but it is the default value and not the value from database.

### Steps to reproduce
I imported the config
`from constance import config`
Then print the result
`config.SOME_CONFIG`

### System configuration
* Django version:  1.11
* Python version: 3.6

**Comment by thongly** [comment]
@jezdez - I'm in a similar situation (wanting to import/export actual settings) and was wondering what the suggested method is for importing/export configs.

Presumably, there could be a way to go about this with a JSON or YAML file, that sets attributes in the config object.

https://github.com/jazzband/django-constance/blob/master/constance/management/commands/constance.py#L26

If there's no suggested way to manage this, and if there is an appetite to include this feature, I'd be happy to send a pull request.

**Comment by jezdez** [comment]
@junejie I'm not sure I'm following, you've updated the config value in the admin, but are not able to access it via the `constance.config` API? Instead you get the default value defined in the settings?

@thongly Can you elaborate what you mean with "wanting to import/export actual settings"? I'm not sure if that's related to the original issue.

**Comment by thongly** [comment]
@jezdez - Sorry.  I read the original question again.  I must have misinterpreted the meaning of the question and/or issue.

I'll start another thread on my question.

**Comment by junejie** [comment]
@jezdez  yes

**Comment by jezdez** [comment]
@junejie Hm, that's strange, since that is completely not how this should work. Could you post more information how you've constance set up? Any chance to see your settings and maybe the code where you can't access the changed value?
