### ISSUE TITLE
Exception when cache is unavailable instead of using db as a fallback

### ISSUE THREAD

**Issue by YvonneYamin** [jazzband/django-constance#236]
### Describe the problem
when using django-constance[database] with CONSTANCE_DATABASE_CACHE_BACKEND as redis cache and the redis is unavailable an exception is thrown instead of using the db as a fallback

### Steps to reproduce
1. start db
2. start redis
3. add CONSTANCE_DATABASE_CACHE_BACKEND to settings.py with the redis config
4. try to get some config value and after it success, shutdown redis and try again to use the same config.
5. exception is thrown - redis is unavailable

### System configuration

* Django version: 1.8.18
* Python version: 2.7
* django-redis: 4.8.0

**Comment by jezdez** [comment]
The database backend doesn't support this kind of behavior, it requires the cache to be available. The reason is simple: Django's cache backend system doesn't offer diagnostic hooks to ascertain if the cache backend is responsive, so it's impossible to implement a generic solution.

**Comment by ambientlight** [comment]
@jezdez: does it make sense giving an option for fallback to config default values in such case? roughly something like:

```py
from redis.exceptions import ConnectionError
from django.conf import settings
from constance import config as _config
from logging import getLogger
logger = getLogger(__name__)

CONFIG = getattr(settings, 'CONSTANCE_CONFIG', {})


class Config:
    """
    Naive fallback on top of constance config to use original defaults when cache backend is unreachable
    """
    def __getattr__(self, key):
        try:
            return _config.__getattr__(key)
        except ConnectionError as e:
            logger.error(e)
            val, _comment = CONFIG[key]
            return val
        except KeyError:
            raise AttributeError(key)

    def __setattr__(self, key, value):
        try:
            _config.__setattr__(key, value)
        except ConnectionError as e:
            logger.error(e)
            logger.error("redis is unavailable, constance update failed")

    def __dir__(self):
        try:
            return _config.__dir__()
        except ConnectionError as e:
            logger.error(e)
            return CONFIG.keys()


config = Config()
```
