### ISSUE TITLE
Constance does not support files

### ISSUE THREAD

**Issue by SebCorbin** [jazzband/django-constance#241]
### Describe the problem

Hello, I'm reopenig the #141 issue as it is really fixed

### Steps to reproduce

request.FILES is not sent to the form, leading to files not being saved

### System configuration

* Django version: 1.11
* Python version: 3.5

**Comment by camilonova** [comment]
@SebCorbin Please try this https://github.com/jazzband/django-constance/pull/242

**Comment by camilonova** [comment]
Should be working by now.
