### ISSUE TITLE
problem with django-admin_tools 0.8.1

### ISSUE THREAD

**Issue by shtalinberg** [jazzband/django-constance#244]
### Describe the problem
AttributeError: 'Meta' object has no attribute 'concrete_model'

Tell us about the problem you're having

 File "admin_tools/dashboard/templatetags/admin_tools_dashboard_tags.py", line 117, in admin_tools_render_dashboard_css
    dashboard = get_dashboard(context, location)
  File "admin_tools/dashboard/utils.py", line 28, in get_dashboard
    return get_app_index_dashboard(context)
  File "admin_tools/dashboard/utils.py", line 92, in get_app_index_dashboard
    ), context)(app_title, model_list)
  File "admin_tools/dashboard/dashboards.py", line 212, in get_app_content_types
    in self.get_app_model_classes()]

### Steps to reproduce
Tell us how to reproduce it
go to /admin/constance/
### System configuration

* Django version:
1.8-11.7
* Python version:
2.7.x

**Comment by jezdez** [comment]
Hm, seems like this is a compatibility issue with the way constance handles the admin integration via a fake model class. The `constance.admin.Config.Meta` class probably just needs another class attribute of `concret_model` pointing at `constance.admin.Config` to satisfy the Django `contenttypes` app to treat that fake model as a legitimate model.

**Comment by skunkie** [comment]
Here is a workaround for `admin.py`:
```
from constance.admin import Config, ConstanceAdmin
from django.contrib import admin


class FixedConstanceAdmin(ConstanceAdmin):

    def __init__(self, model, admin_site):
        model._meta.concrete_model = Config
        super().__init__(model, admin_site)


admin.site.unregister([Config])
admin.site.register([Config], FixedConstanceAdmin)
```
