### ISSUE TITLE
Constance in multiprocess environment

### ISSUE THREAD

**Issue by Ashish-Bansal** [jazzband/django-constance#248]
Hi everyone,

I wanted to know what will happen if we run constance in multiprocess environment. 
Let's say there are two instances of same django application running behind a load balancer, connected to same backend. Will updating the value on one instance cause `config_updated` signal to be triggered on other instance too ? 

Regards,
Ashish Bansal

**Comment by SebCorbin** [comment]
Off the top of head, I would say no, signals are not meant to be sent/received across workers or threads. From the [docs](https://docs.djangoproject.com/en/3.0/topics/signals/), it's used for signaling other apps of changes, facilitating decoupling.

Now in the context of django-constance, as long as your other threads/workers are getting constance settings from the same instance (redis/db/cache), you should be safe, but it really depend on the usage of your constance settings.

**Comment by SebCorbin** [comment]
Linking #343 for an example of problem that may rise in tests.
