### ISSUE TITLE
pip release

### ISSUE THREAD

**Issue by FabrizioMontanari** [jazzband/django-constance#251]
I'm currently working on a project which use Constance to manage some settings.
This project rely on pip to install django-constance, but the current pip release has a bug regarding
File Upload.
The bug was solved on [issue #242](https://github.com/jazzband/django-constance/pull/242), but the fix is not on pip yet.

I would like to know if there is an update for pip planned in the near future, to decide if removing those field from Constance or to wait for the new release.

**Comment by camilonova** [comment]
Done
