### ISSUE TITLE
upgrading from 2.0.0 to 2.1.0 breaks the admin  

### ISSUE THREAD

**Issue by IvonYaminDahan** [jazzband/django-constance#255]
### Describe the problem
When upgrading from 2.0.0 to 2.1.0 it breaks the admin.
In the ConstanceForm.clean method there is a check if settings.FIELDSETS and settings.CONFIG has the same amount of keys.
In my case I didn't configured the FIELDSETS, so it is empty and it causes a validation error when trying to update the values.  

### Steps to reproduce
Define only settings.CONFIG
Open the admin and try to edit any key

### System configuration

* Django version: 1.8
* Python version: 2.7

**Comment by blablacio** [comment]
Relevant PR: https://github.com/jazzband/django-constance/pull/256

**Comment by camilonova** [comment]
Please check if current master fixes your issue so we can close this.

**Comment by rmaciejczyk** [comment]
I just experienced the same issue. I tried the current master but it doesn't resolve it. If there is no CONSTANCE_CONFIG_FIELDSETS defined in the settings.py file the form fails silently while saving so all the constance values stay unsaved.

**Comment by rmaciejczyk** [comment]
I had the same issue (Django 1.8, Python 2.7) and it seems that the current master code fixes it

**Comment by camilonova** [comment]
It is fixed.
