### ISSUE TITLE
Fields are not visible in admin with Grapelli unless Constance precedes everything else in INSTALLED_APPS 

### ISSUE THREAD

**Issue by ilebedie** [jazzband/django-constance#270]
### Describe the problem
My project uses Grappelli extension for django admin and unless Constance is mentioned before Grapelli, Constance fields would not show up(though Constance config is visible in admin). My settings.py that works after all:
```
INSTALLED_APPS = (
    'constance',
    'grappelli',
    'nested_admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.admin',
```
Took me some time to figure out. Should this perhaps be documented? 
Thanks! 

### System configuration
* Django version: 1.8
* Python version: 2.7

**Comment by camilonova** [comment]
Please document it and make a pull request. I'll be happy to merge it. Thanks.
