### ISSUE TITLE
Look for a specific configuration

### ISSUE THREAD

**Issue by tiagocborg** [jazzband/django-constance#279]
Why is not possible to iterate constance.config?

I need to look for a specific option on my config, so I wanted to iterate on the config, something like this:
`for option in config:`
       `if option == random_value:`
                 `do_stuff`

I know I can access with config.MY_OPTION, but I need to look if a random value I might receive is there.

Any hint?

**Comment by yinkanghong** [comment]
If i'm figure right,you want to get constance value in view? If so,this code can be help:

```
from constance import LazyConfig
config = LazyConfig()

def put_value(key, value):
    """
    update key value
    :param key:key 
    :param value: value
    :return: None
    """
    setattr(config, key, value)


def get_value(key):
    """
    get value by key
    :param key: key 
    :return: value
    """
    return getattr(config, key)
```

**Comment by Pronjaboy** [comment]
Thanks @yinkanghong , but that is not it. I've edited my question to be more clear.

**Comment by yinkanghong** [comment]
```
from constance.settings import CONFIG
print(CONFIG)
```
see this is what you need?
