### ISSUE TITLE
Ordered fieldsets, how to?

### ISSUE THREAD

**Issue by stitch** [jazzband/django-constance#280]
### Describe the problem
Documentation is missing information about being able to have sorted CONSTANCE_CONFIG_FIELDSETS. While ordering on fields is clear, ordering on fieldsets isn't (and might not seem to be supported?). It would help to present things in a meaningful order. 

### Steps to reproduce
Missing here: https://django-constance.readthedocs.io/en/latest/

### System configuration

* Django version:  2.0
* Python version: 3.6

**Comment by stitch** [comment]
Simple workaround is to simply number the label of the fieldset, like so:

![image](https://user-images.githubusercontent.com/333846/39470088-03dab6e8-4d3c-11e8-9394-650bf5db1a34.png)

(you might want to use zero width characters, so it's not even noticeable :))

**Comment by a1tus** [comment]
Hi guys. Docs says to use `OrderedDict` for fields here:
https://django-constance.readthedocs.io/en/latest/#ordered-fields-in-django-admin

And it also works for fieldsets.

**Comment by stitch** [comment]
I stand corrected! I was mixing up syntaxes between the normal config and dictconfig which resulted in "ValueError: need more than 1 value to unpack". I've taken a good look at the OrderedDict example and applied it to CONSTANCE_CONFIG_FIELDSETS and this works like a charm.

![image](https://user-images.githubusercontent.com/333846/39513187-cf4eb89e-4df3-11e8-8539-0506aace21e2.png)

@a1tus Thank you for your comment! :))
