### ISSUE TITLE
Can not install the django-constance.

### ISSUE THREAD

**Issue by moonshineBoy** [jazzband/django-constance#284]
### Describe the problem

I can not install the django-constance.

### Steps to reproduce

$ pip3 install django-constance
Collecting django-constance
  Could not fetch URL https://pypi.python.org/simple/django-constance/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement django-constance (from versions: )
No matching distribution found for django-constance

### System configuration

* Django version: 
$ django-admin --version 
1.11.1

* Python version:
$ python3 --version
Python 3.5.2

$ pip3 --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)

**Comment by jezdez** [comment]
This is an unrelated pip installer issue, please upgrade to the latest version and try again.
