### ISSUE TITLE
Using Local-memory as Redis replacement in test environment

### ISSUE THREAD

**Issue by Jastrzebowski** [jazzband/django-constance#285]
### Describe the problem

I'm using Redis as a backend for both caching and Constance, in my test env I'm replacing Redis with Local-memory caching. How should I use Constance in this setup?

### System configuration

* Django version: 2.0.5
* Python version: 3.6.5

**Comment by belyak** [comment]
Really important. At the moment I work on the system with sophisticated data processing and it is very uncomfortable to restore local Constance settings every time after the unit-tests run (I have to use and unit and manual testing locally)
As a workaround you can so the next:
(in settings.py)

```
TEST_MODE = 'test' in sys.argv

if TEST_MODE:
    # change constance DB to preserve existing local settings:
    CONSTANCE_REDIS_CONNECTION = 'redis://localhost:6379/1'


```

**Comment by bmwant** [comment]
See this PR https://github.com/jazzband/django-constance/pull/394

**Comment by Mogost** [comment]
Done in #394
