### ISSUE TITLE
Problem rendering constance with django_admin_bootstrapped

### ISSUE THREAD

**Issue by mizamae** [jazzband/django-constance#286]
Hello,

Firstly I have to say it is a very nice tool and idea.

### Describe the problem
I am having some issues rendering constance in a application using django_admin_bootstrapped.
More precisely, the table renders very ugly without any style...
![captura](https://user-images.githubusercontent.com/10700202/40233199-47e7885c-5aa2-11e8-9d6e-80ac25e6c295.PNG)

can it be just an issue of django_admin_bootstrapped?? This is the way it renders some other models...

![captura](https://user-images.githubusercontent.com/10700202/40233296-b63f01fe-5aa2-11e8-9611-4ffcc38b589e.PNG)

### Steps to reproduce

Simply followed your guide to use it.

### System configuration

* Django version: 1.11.2
* Python version: 3.4

**Comment by aymaneMx** [comment]
same, how did you solve this @mizamae, please?

**Comment by mmodenesi** [comment]
Same question here.

Using django 1.8, django-admin-bootstraped 2.5.7, django-constance==2.7.0

Hack:

I just copied the relevant templates to my `<rootdir>/templates/...` (to force loaders find my version first) and changed some markup to match django-admin-bootstrapped (both tags and classes)

For example:

```
root@host:/usr/src/app# diff /usr/local/lib/python3.4/dist-packages/constance/templates/admin/constance/change_list.html templates/admin/constance/

60,62c64,66
<             <p class="paginator sticky-footer">
<               <input type="submit" name="_save" class="default" value="{% trans 'Save' %}"/>
<             </p>
---
>             <div class="pull-right">
>               <input type="submit" name="_save" class="btn btn-primary default" value="{% trans 'Save' %}"/>
>             </div>
69,73c73,78
< <div class="breadcrumbs">
<   <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
<   &rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
<   &rsaquo; {{ opts.verbose_name_plural|capfirst }}
< </div>
---
> <ul class="breadcrumb">
>   <li><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
>     <li><a href="{% url 'admin:app_list' app_label=opts.app_label %}">{% with app_label=opts.app_config.verbose_name|default:opts.app_label %}{{ app_label|title }}{% endwith %}</a></li>
>     <li>{{ opts.verbose_name_plural|capfirst }}</li>
>     </ul>
> 
```

And 

```
root@host:/usr/src/app# diff /usr/local/lib/python3.4/dist-packages/constance/templates/admin/constance/includes/results_list.html templates/admin/constance/includes/
3c6
<     <table>
---
>     <table class="table table-striped table-bordered" id="result_list">
```

I wonder what's the *right* way to do it, though
