### ISSUE TITLE
Changing value type (for example int -> datetime.timedelta) does not invalidate value, stored in database

### ISSUE THREAD

**Issue by PeterBeklemishev** [jazzband/django-constance#288]
### Describe the problem

Changing value type (for example int -> datetime.timedelta) does not invalidate value, stored in database

### Steps to reproduce

* Create constance_config entry with `int` value
* Modify value via admin interface
* Change default value in config to datetime.timedelta instance
* Try to get this value via `costance.<OUR_KEY_NAME>` - it will return `int` instead of `timedelta`

### System configuration

* Django version: 2.0.x
* Python version: 3.5

**Comment by syurchenko** [comment]
[Django datamigrations](https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations) for next version of project solve this issues.
There is no robust way to migrate data between different types automatically.
