### ISSUE TITLE
Views to expose custom settings via DRF  (feature request)

### ISSUE THREAD

**Issue by AGranero12** [jazzband/django-constance#291]
I am building a project in which I need to have a few custom settings that are editable by certain users which do not have access to the django admin panel, who access the application via an Angular frontend. I installed django-constance in order to have these custom settings editable, but I am missing the functionality to expose those settings on my API rest via django rest framework

It would be great if some views could be provided in order to retrieve and update the customized settings easily in decoupled applications.

Thanks in advance!

* Django version: 2.0.7
* Python version: 3.6.6

**Comment by camilonova** [comment]
I think this is out of the scope for this library, seems a better fit to make your custom backend using the constance low level api.

Regards.

**Comment by AGranero12** [comment]
@camilonova I understand, thanks for the tip!

@yinkh  Thank you very much for the demo! I will try to go ahead with this. I also posted a question [here](https://stackoverflow.com/questions/51360970/how-to-expose-django-constance-settings-via-django-rest-framework/) where you might want to share your answer.
