### ISSUE TITLE
Hashing of values

### ISSUE THREAD

**Issue by sneela223** [jazzband/django-constance#298]
Hello,

I see that django-constance hashes the values being stored to database using hashlib and md5. But I don't want the values to be encrypted. Is there any way I can avoid the hashing?

Thanks in advance.

### System configuration

* Django version: 2.0
* Python version: 3.6

**Comment by norozap** [comment]
Hi. I was looking to avoid the hashing as well but I ended up modifying the constance model, by adding a regular charfield column to the table, ran makemigrations database / migrate database and then assigned the value to the newly created field before the object save:

`
# File: backend/database/models.py
...
class Constance(models.Model):
    key = models.CharField(max_length=255, unique=True)
    value = PickledObjectField()
    value_text = models.CharField(max_length=255, null=True)
...
`

`
# File: backends/database/__init__.py
...
       if not created:
            constance.value = value
            constance.value_text = value
            constance.save()
        if self._cache:
...
`

Once I did all the changes, I tried editing/saving the Config from the Admin, and the value was stored in plain text on my newly created column.

Hope this helps!

**Comment by zodman** [comment]
If you refer the md5 its used for check the version on ConstanceForm

If you using the database module constance use the PickeObject its a base64 hash.

You can decode it and show the variable, using dbsafe_decode 

https://github.com/gintas/django-picklefield/blob/master/src/picklefield/fields.py#L62
