### ISSUE TITLE
put constance before you application in INSTALLED_APPS

### ISSUE THREAD

**Issue by horida** [jazzband/django-constance#304]
I got the following error accessing the admin page when `constance` was included after my custom apps in `settings.py` `INSTALLED_APPS`:

```
django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': 'constance'}' not found. 1 pattern(s) tried: ['admin/(?P<app_label>auth|backend)/$']
```

Moving it before my custom apps solved the problem. In case that is a general "feature" it is worth mentioning it in the documentation.

Django 2.0.3
Python 3.6.6
constance 2.3.0
### System configuration

* Django version:
* Python version:

**Comment by chadsaun** [comment]
Thank you! This actually fixed my issue when I was getting the following error:

```
ValueError
Missing staticfiles manifest entry for 'admin/css/constance.css'
```

**Comment by horida** [comment]
@camilonova could you please elaborate why you closed the issue? 
Thank you

**Comment by camilonova** [comment]
@horida because this was documented in https://github.com/jazzband/django-constance/commit/886f6d523563c6be324d4284eb2384489c464281
