### ISSUE TITLE
Idea: Interest in advanced example showing DRY front-end forms with settings from specific fieldset?

### ISSUE THREAD

**Issue by OmenApps** [jazzband/django-constance#305]
For my own project I needed to create front-end Constance forms that displayed only the settings for specific fieldsets. In my particular project, my Constance settings are split among 4 different fieldsets, and I wanted to display these settings separately in forms on tabs in a view. Each tab displays a form with only the settings for a specific formset, and each form can be submitted separately from the others. Similarly, I could add a view with just the content from one fieldset, multiple fieldsets, or all the fields, utilizing the same Form class.

The idea is similar to [Issue 273](https://github.com/jazzband/django-constance/issues/273) by @gustavi but was created independent of his work, and focuses on using Constance's built-in fieldsets, rather than declaring individual fields, in order to simplify and make things DRY.

Would there be interest in a pull request that demonstrates all of this functionality? If there is, I'll be happy to extract the relevant content from my project.

If there is interest, should I add this as a separate example project, or overwrite the existing example project?

**Comment by zodman** [comment]
make a PR i will review it!
