### ISSUE TITLE
Is it possible to programmatically change the constance value?

### ISSUE THREAD

**Issue by littlehome-eugene** [jazzband/django-constance#308]
It's a question.  

Is it possible to modify the value programatically without using the admin interface?

**Comment by yinkh** [comment]
Yes

	from constance import config

	def set_value(key, value):
	    """
	    update settings
	    :param key
	    :param value
	    :return: None
	    """
	    setattr(config, key, value)
	
	
	def get_value(key):
	    """
	    get settings
	    :param key
	    :return: value
	    """
	    return getattr(config, key)

usage:

	set_value('site_name', )
	get_value('site_name') # should be 'this is demo'

**Comment by littlehome-eugene** [comment]
ps. config.key = value seems to work fine
