### ISSUE TITLE
[SOLVE] [SOLVE] Fix django-constance styles with grappelli. Before grappelli or after?

### ISSUE THREAD

**Issue by johncpang** [jazzband/django-constance#314]
### Describe the problem

Admin of constance config has not style of grappelli.

According to doc, 

> If you use admin extensions like Grapelli, 'constance' should be added in INSTALLED_APPS before that extension

However, the admin page will lose all styling unless 'constance' is placed *after* 'grappelli'.

### Steps to reproduce

To get the un-styled admin:

	INSTALLED_APPS = [
		'django.contrib.contenttypes',
		'constance',  # before grappelli
		'grappelli.dashboard',  # after django.contrib.contenttypes, before grappelli
		'grappelli',  # before django.contrib.admin
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.sessions',
		'django.contrib.messages',

Moving `constance` right after `grappelli` will solve the problem.

### System configuration

* Django version: 2.1.5
* Python version: 3.6

**Comment by zodman** [comment]
this not a issue rename the title with something 

[SOLVE] Fix django-constance styles with grapelli. and close the issue
