### ISSUE TITLE
Feature request: Improve admin screen

### ISSUE THREAD

**Issue by charleswhchan** [jazzband/django-constance#316]
When viewing the admin screen, django-constance shows a list containing all the options and a single save button for all options.

Would it be able to have the list be readonly? When user clicks on a single option, to have it open a page for 1 specific config with a save button to change only one config?

This would avoid accidentally updating other config unexpectedly and is more consistent with other Django admin screens (such as user admin).

Thoughts?

**Comment by camilonova** [comment]
You can contribute anytime. Seems like a great feature to me.
