### ISSUE TITLE
Update docs at readthedocs for 2.4.0 version

### ISSUE THREAD

**Issue by DmytroLitvinov** [jazzband/django-constance#323]
### Describe the problem

The documentation is not updated for version 2.4.0(stable and latest version)

### Steps to reproduce

Enter https://django-constance.readthedocs.io/en/latest/changes.html or https://django-constance.readthedocs.io/en/stable/changes.html

**Comment by camilonova** [comment]
@jezdez

**Comment by jezdez** [comment]
Looking..

**Comment by jezdez** [comment]
Not sure what went wrong, but re-saving the RTD settings rebuilt the docs. I also set up the incoming webhook again, since there wasn't any for some reasons. Let me know if the problem persists.
