### ISSUE TITLE
Does constance supports password field?

### ISSUE THREAD

**Issue by rafaelreuber** [jazzband/django-constance#327]
I wish to "hide" (at least on Django Admin) some specific config values. Does constance have support password field?

**Comment by 0xbart** [comment]
Yes, I think this is you're looking for.

```
'secret_password_field': [
        'django.forms.fields.CharField', {
            'widget': 'django.forms.PasswordInput'
        }
]
```

**Comment by rafaelreuber** [comment]
Yes, is it! Thank you.

**Comment by srtab** [comment]
Passing `widget_kwargs` with `render_value=True` avoid the need to introduce the password every time that you save the configs:

```python
'secret_password_field': [
    'django.forms.fields.CharField', {
        'widget': 'django.forms.PasswordInput',
        'widget_kwargs': {'render_value': True}
    }
]
```

**Comment by Ricardomol** [comment]
> Passing `widget_kwargs` with `render_value=True` avoid the need to introduce the password every time that you save the configs:
> 
> ```python
> 'secret_password_field': [
>     'django.forms.fields.CharField', {
>         'widget': 'django.forms.PasswordInput',
>         'widget_kwargs': {'render_value': True}
>     }
> ]
> ```
@0xbart, @srtab thanks for your answer.
But excuse my ignorance, where would that code go?

**Comment by Mogost** [comment]
JFYI when you click the save button all variables from the page are sent to the server.
In this case you need type your password every time you save something on the page.
> ```
> 'secret_password_field': [
>         'django.forms.fields.CharField', {
>             'widget': 'django.forms.PasswordInput'
>         }
> ]
> ```

In this case your password will always be given on the page (and will not be safe from people who can enter the page).
> ```
> 'secret_password_field': [
>     'django.forms.fields.CharField', {
>         'widget': 'django.forms.PasswordInput',
>         'widget_kwargs': {'render_value': True}
>     }
> ]
> ```
