### ISSUE TITLE
Problems with giving permissions to a user in Django Admin (403 Forbidden)

### ISSUE THREAD

**Issue by yigitgenc** [jazzband/django-constance#332]
### Describe the problem

I gave specific permission to a user in `Django Admin` in order to give access only for specific tables (in this case, to the `Constance Config` table); but the user is still not able to see Constance Config section in Django Admin. It raises `403 Forbidden` error.

### Steps to reproduce

1) Log-in to Django Admin
2) Give a user permissions only for Constance Table / Database
3) Let the user show/view the Constance Table / Database
4) The user will see the 403 Forbidden error.

Screenshot: 
<img width="417" alt="Screenshot 2019-06-28 at 16 14 44" src="https://user-images.githubusercontent.com/306731/60349613-3f869300-99c2-11e9-8711-415a66a213b5.png">

### System configuration

* Django version: 2.1.9
* Python version: 3.7.3

**Comment by creativequality** [comment]
Same problem here.
Any news?

**Comment by dtcooper** [comment]
Also have run into this!

**Comment by Mogost** [comment]
Add that to config.
```python
CONSTANCE_SUPERUSER_ONLY = False
```

That is due to code:
```python
    def has_change_permission(self, request, obj=None):
        if settings.SUPERUSER_ONLY:
            return request.user.is_superuser
        return super().has_change_permission(request, obj)
```
And it's documented:
https://django-constance.readthedocs.io/en/latest/index.html#editing
Maybe some changes are needed, but I'm not sure. 
cc: @camilonova
