### ISSUE TITLE
How can i add a subfolder for file uploads?

### ISSUE THREAD

**Issue by kaganuk** [jazzband/django-constance#334]
### Describe the problem
> Images are uploaded to MEDIA_ROOT.

I want to set a subfolder after my MEDIA_ROOT for each image_field item. Otherwise it's saving all files to MEDIA_ROOT and it doesn't satisfy my requirements.

### Steps to reproduce
We can add a special parameter like upload_to and this parameter is helps us for setting subfolder. If anyone directs me i can contribute for it.

### System configuration

* Django version: 1.11.22
* Python version: 2.7.16

**Comment by camilonova** [comment]
Is out of the scope of this library. Thank you.

**Comment by rvernica** [comment]
Is there any other way to have images uploaded to a different folder, say `MEDIA_ROOT\constance`?
