### ISSUE TITLE
Default value for float field separated by comma instead point in admin interface

### ISSUE THREAD

**Issue by HenryPro10** [jazzband/django-constance#339]
### Describe the problem

If I have default value for float option of constance config, it render with comma in admin interface. If I click on the default value and then try to save constance config, I will have type error message. Is it normal?

### Steps to reproduce

Add this constance config:

`CONSTANCE_CONFIG = {
    'TEST_FIELD': (0.02, 'Example', float),
}`

### System configuration

* Django version:
* Python version:

Python 3.6.3

Django==2.1.5
django-constance==2.4.0

**Comment by Rotzbua** [comment]
Observed the same behavior for `django-constance==2.7.0`.
Seems that the default value is not rendered language dependend. If custom value is set, everything is fine.

**Comment by sergei-iurchenko** [comment]
it is fixed in recent version

**Comment by devmitrandir** [comment]
Again

```python
CONSTANCE_CONFIG = {
    'FLOAT_VALUE': (3.1415926536, 'PI'),
}
```
![image](https://github.com/user-attachments/assets/d9cf310d-95f4-4e52-8a50-aa9dbc9aefd7)

Django==5.0
django-constance==4.1.0

**Comment by Mogost** [comment]
PR is welcome
