### ISSUE TITLE
Compatibility issue with Django 3.0 due to django.utils.six

### ISSUE THREAD

**Issue by Mogost** [jazzband/django-constance#341]
Django 3.0 scheduled for December removed Python 2 compatibility API used by django-constance (django.utils.six).

See https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis
It would be wise to switch now to the direct use of six.

### System configuration

* Django version: 3.0a1
* Python version: 3.6

**Comment by jezdez** [comment]
Sure, PRs are welcome. Don't forget to add six to the installation requirements.

**Comment by marco-silva0000** [comment]
as django 3 was released 3 days ago, can we get a new release of django-constance with this fix?
