### ISSUE TITLE
400 on saving

### ISSUE THREAD

**Issue by VivienGiraud** [jazzband/django-constance#347]
### Describe the problem

Clicking on `save` returns a `400` error, clicking on `reset to default` just do nothing at all (no request).

### Steps to reproduce

I just installed constance with database backend.
Added so test data.
```
CONSTANCE_CONFIG = {
    'TEST': (False, 'Activate TEST', 'yes_no_null_select'),
}
CONSTANCE_CONFIG_FIELDSETS = {
    'Aggregators': ('TEST',),
}

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_null_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((None, "-----"), (True, "Yes"), (False, "No"))
    }],
}
```
Data can be seen on `/config` but not write. I hand wrote it on DB, the value changed on constance, but still not able to update it via `/config` page.

### System configuration

* Django version: 2.1
* Python version: 3.7.4

**Comment by arycloud** [comment]
I have solved that issue by applying migrations, simple using: `python manage.py migrate`

**Comment by Mogost** [comment]
Hope migrations help
