### ISSUE TITLE
Provide a 'setting_defaults' backend for testing

### ISSUE THREAD

**Issue by RichardForshaw** [jazzband/django-constance#349]
### Describe the problem

I have an issue/request that is similar to #285. In production and integration testing I run a redis backend, but in an effort to minimize complexity when running unit tests I want to be able to minimize the additional services that are running, such as redis.

### Suggested improvement

My suggestion is to have some kind of 'defaults' backend, which will simply return the default values defined in the `CONSTANCE_CONFIG` structure, unless they are overridden with an `override_config` directive. I suspect that this is reasonable behaviour when writing unit tests, as you will tend to use setting defaults unless you specifically want to exercise the setting values.

### Steps to reproduce

This is a request rather than an issue. The current behaviour is standard.

### System configuration

* Django version: N/A
* Python version: N/A

**Comment by bmwant** [comment]
@RichardForshaw check out this PR https://github.com/jazzband/django-constance/pull/394

**Comment by camilonova** [comment]
This will be addressed in #394
