### ISSUE TITLE
Domain based schema switching and constance[redis]

### ISSUE THREAD

**Issue by JacoBezuidenhout** [jazzband/django-constance#352]
To start, thank you for this awesome plugin! We currently have a single instance webapp running multiple tenants. Constance is being used to Whitelabel the different tenants based on the domain name of the request. This works well with the database backend because we split tenant data using postgres schemas. 

Do you perhaps have a way for us to dynamically (in middleware) change the 
---- CONSTANCE_REDIS_PREFIX = 'constance:myproject:' setting during runtime?

**Comment by Mogost** [comment]
You can develop a custom `CONSTANCE_REDIS_CONNECTION_CLASS` to do that.
