### ISSUE TITLE
Command to remove stale records in db

### ISSUE THREAD

**Issue by syurchenko** [jazzband/django-constance#354]
### Describe the problem

Actively maintained projects add and remove constants to config but they are never actually deleted from db. I added option to constance command to delete stale records from db.

Usage:
`./manage.py constance remove_stale_keys`

Records are deleted only from database. Redis keys are considered to expire eventually.

### Steps to reproduce

- Add some constant to config
- Run your django application
- Check that constant exists in db
- Remove constant from config
- Check that constant still exists in db

### System configuration

* Django version: any
* Python version: any

Merge request
https://github.com/jazzband/django-constance/pull/355

**Comment by Voltoran** [comment]
Really useful option. Have same problems in my project.
