### ISSUE TITLE
Cannot save config when deploy using docker stack with multiple node app

### ISSUE THREAD

**Issue by reizajudiz** [jazzband/django-constance#356]
### The problem
The problem occured when deploying with docker stack multiple node. When I try to save the configuration it return validation error on the top of the page saying **"The settings have been modified by someone else. Please reload the form and resubmit your changes."**
maybe it appeared because POST data transfered to other node than the requested node. is it possible to disable the validation? So I would not make any specific configuration on routing URL on my traefik configuration
 
### Steps to reproduce
You have to prepare the whole django project running on docker swarm mode with multiple node

### System configuration
* Django version: 2.1.10
* Python version: 3.5

 Sorry if you can't understand because of my bad english. Thanks

**Comment by dmartin** [comment]
This may help: https://django-constance.readthedocs.io/en/latest/index.html
>django-constance’s hashes generated in different instances of the same application may differ, preventing data from being saved.
>
>Use this option in order to skip hash verification.
>
>CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True
