### ISSUE TITLE
add compatibility to django 3.0

### ISSUE THREAD

**Issue by domdinicola** [jazzband/django-constance#357]
this implies handling of six

**Comment by jezdez** [comment]
This has been fixed in https://github.com/jazzband/django-constance/commit/db3f6e6e2fc57c49a5cbe2d4e78c7b0d4c259903.

**Comment by Mogost** [comment]
@jezdez I seem a little overlooked this:
https://github.com/jazzband/django-constance/blob/master/tests/settings.py#L2
It seems to me wiser to put more effort into #359 PR.

**Comment by domdinicola** [comment]
I guess now we need a new release

**Comment by Mogost** [comment]
Six is not only one problem.

**Comment by domdinicola** [comment]
@Mogost so I guess we cannot close the issue...

**Comment by Mogost** [comment]
I agree. Compatibility at present is not ensured.
I have already done PR and expect a review from @jezdez.
If someone else is ready to check PR, you are welcome. #359 
There is a [test ](https://github.com/jazzband/django-constance/pull/359#discussion_r356675678) that I commented out (I could not cope with it, if someone is ready to pay attention to this test, I will be grateful.).
