### ISSUE TITLE
add compatibility to python 3.8

### ISSUE THREAD

**Issue by domdinicola** [jazzband/django-constance#358]

**Comment by frank-io** [comment]
Hi there, has it been tested with python3.8 yet? Cheers

**Comment by Natureshadow** [comment]
The current version works perfectly with Python 3.8 (and I do not see why it should ever have not worked — Python 3.8 was never an issue, only Django 3.0 vs. Django 1.11 was).

**Comment by domdinicola** [comment]
I think it was not tested in travis at that moment
