### ISSUE TITLE
[Improvement] TypeError: 'Config' object is not subscriptable

### ISSUE THREAD

**Issue by bartmachielsen** [jazzband/django-constance#360]
### Describe the problem

It would be a usefull feature if you can dynamically call the variables in constance. Small addition by adding the method `def __getitem__(self, key):` to the Config class.

### Steps to reproduce
Don't use the `config.SOME_CONSTANCE_VARIABLE` method but call by string.
`config['SOME_CONSTANCE_VARIABLE']`

Work around is to call the get_attr function directly (but not the most prettiest option)

**Comment by camilonova** [comment]
@jezdez Do you think is something we should do?

I'm not sure if we should allow Constance to work as a dict.

**Comment by Mogost** [comment]
This seems like a reasonable change, but if it is accepted, documentation must be added.
I would start the discussion by answering the question “why not?”.

**Comment by jezdez** [comment]
We shouldn't make the Config class a hybrid container since it'd would just be a matter of time till people wonder why it doesn't have all the dict behaviors. It's perfectly valid to use `getattr` for this kind of use case.
