### ISSUE TITLE
Does not respect decimal precision context for default display

### ISSUE THREAD

**Issue by rickrcomm** [jazzband/django-constance#363]
### Describe the problem
Constance does not appear to respect decimal precision context for default value display in the Admin menu

From settings.py:
----------------------------------------------------------------
ctx = Context(prec=2)
setcontext(ctx)
CONSTANCE_CONFIG = OrderedDict([
    ('PRICE_LOW_1', (Decimal(0), 'Price Range 1 - LOW')),
    ('PRICE_HIGH_1', (Decimal(99.99,ctx), 'Price Range 1 - HIGH')),
    ('PRICE_OFFSET_1', (Decimal(10), 'Price Range 1 - OFFSET')),
])
----------------------------------------------------------------

Default display of PRICE_HIGH_1 is 99.9899999999999948840923025272786617279052734375

![image](https://user-images.githubusercontent.com/374912/71314646-c36d8500-2411-11ea-8d71-81d357a71425.png)

### System configuration

* Django version:3.67
* Python version:1.11.25

**Comment by Mogost** [comment]
Decimal is not in supported types
https://django-constance.readthedocs.io/en/latest/#custom-fields

**Comment by rickrcomm** [comment]
???  Decimal is the 4th type in the supported types list you linked. I don’t understand????

But I think the first paragraph under custom fields says that I should have put decimal as the third tuple which I did not do. Isn’t that right?

Rick


> On Dec 22, 2019, at 12:18 PM, Alexandr Artemyev <notifications@github.com> wrote:
> 

﻿
Decimal is not in supported types
https://django-constance.readthedocs.io/en/latest/#custom-fields

**Comment by Mogost** [comment]
Oops, I missed.
But raw python has same result:
```
>>> ctx = Context(prec=2)
>>> setcontext(ctx)
>>> Decimal(99.99,ctx)
Decimal('99.9899999999999948840923025272786617279052734375')
```
if you want just 99.99 you can use quotes like
```
>>> Decimal('99.9')
Decimal('99.9')
```
or for django-constance
```
CONSTANCE_CONFIG = OrderedDict([
('PRICE_HIGH_1', (Decimal("99.99"), 'Price Range 1 - HIGH')),
])
```

**Comment by rickrcomm** [comment]
Thank you very much.  Solves the problem.

Rick

**Comment by rickrcomm** [comment]
Quick question. Is there a way to have Constance store the values in the database unencrypted/unhashed so you can see what they are from SQLiteStudio?

Rick

> On Dec 22, 2019, at 1:05 PM, Alexandr Artemyev <notifications@github.com> wrote:
> 

﻿
Oops, I missed.
But raw python has same result:

>>> ctx = Context(prec=2)
>>> setcontext(ctx)
>>> Decimal(99.99,ctx)
Decimal('99.9899999999999948840923025272786617279052734375')
if you want just 99.99 you can use quotes like

>>> Decimal('99.9')
Decimal('99.9')
or for django-constance

CONSTANCE_CONFIG = OrderedDict([
('PRICE_HIGH_1', (Decimal("99.99"), 'Price Range 1 - HIGH')),
])

**Comment by Mogost** [comment]
That is on https://github.com/gintas/django-picklefield layer.
You can use https://docs.python.org/3/library/pickle.html#data-stream-format
>Protocol version 0 is the original “human-readable” protocol and is backwards compatible with earlier versions of Python.
How to redefine the protocol version you need to figure it out for yourself.
