### ISSUE TITLE
Conflict with django-admin-interface

### ISSUE THREAD

**Issue by python2and3developer** [jazzband/django-constance#365]
### Description of the problem
Constance is replacing the classes applied by other apps in the block `bodyclass` of `admin/base_site.html`.

This generates a conflict for example with `django-admin-interface` because this app add some specific CSS class names in the body to change completely the style of the admin panel.

### Steps to reproduce
1. Create a django project with `constance` and `django-admin-interface`.
The repository and the instructions for the installation of `django-admin-interface` is here: 
```
    https://github.com/fabiocaccamo/django-admin-interface
```
2. Enter the admin panel of django
3. Enter to django-constance admin panel
4. All the style has been lost in that panel. That problem doesn't happen in the admin panel of other models. 

### Solution
To change `admin/constance/change_list.html` adding `{{ block.super }}` in the the block `bodyclass`, like this:
```
   {% block bodyclass %}{{ block.super }} change-list{% endblock %}
```

**Comment by Mogost** [comment]
I see no problem for this change.
PRs are welcome.
