### ISSUE TITLE
Verbose Name and Grouping/Fieldset

### ISSUE THREAD

**Issue by schacki** [jazzband/django-constance#37]
Hi all,

for usability reasons, it would be nice to be able to add a verbose name (that could then also be translatable) and a group name for display as part of a fieldset. 

Regards,
Juergen

**Comment by leesolway** [comment]
One of the suggested solutions in #41 was adding a var CONSTANCE_CONFIGS. 
Is there a plan to implement this feature?

**Comment by michaelkuty** [comment]
we have simple implementation, but we use crispy forms for rendering form and using internal leonardo stuff, from these reason i not maked PR
https://github.com/django-leonardo/django-constance/commit/8a6e8af2b480eeb430587e67d56c6641c8ac6ff8

**Comment by camilonova** [comment]
It's almost ready in #119
