### ISSUE TITLE
Is dynamic INSTALLED_APPS supported ?

### ISSUE THREAD

**Issue by laurent-brisbois** [jazzband/django-constance#373]
### Describe the problem

Does it support dynamic INSTALLED_APPS settings ?
If yes, how is that changed ?
And what if turn off my application and then turn it back on ?

I'm actually trying to implement on-demand installable apps in my applications (during runtime of course)

### System configuration

* Django version: 2.2.5
* Python version: 3.7.3

**Comment by Natureshadow** [comment]
You are welcome to look at https://edugit.org/AlekSIS/AlekSIS for how we do it there.

**Comment by laurent-brisbois** [comment]
Thanks.
I see that you populate your INSTALLED_APPS with more apps with `get_app_packages()`. In settings.py it is done at startup. I guess you keep track of installed apps somewhere and whenever you restart your application this `get_app_packages()` will get them back into INSTALLED_APPS.

Is that right ?

So if I keep track of installed apps in my application I could do the same.

**Comment by Natureshadow** [comment]
It leverages namespaces. `get_app_packages` returns everything under the `aleksis.app` namespace. The second part, which is the one relevant for constance, is `merge_app_settings`, which is used to pull `CONSTANCE_CONFIG` and `CONSTANCE_FIELDSETS` defined in apps into the structures in the project's main `settings.py`.

**Comment by Natureshadow** [comment]
As this is not very specific to constance, it might be better to continue the discussion somewhere else. I have already thought about making a generic DJango module out of that functionality, so a second opinion and use case would be great. Feel free to ping me via e-mail (the one listed in my GitHub profile).

**Comment by laurent-brisbois** [comment]
I managed to do it 100% with Django. Django provides tools with AppConfig that enables to do it.
Since it is also possible to run management commands on runtime, we can run migration commands.
