### ISSUE TITLE
Use Constance setting as value for other setting variable?

### ISSUE THREAD

**Issue by lggwettmann** [jazzband/django-constance#379]
### Describe the problem

Django-Money asks for a CURRENCIES variable in the django.settings file. I want to provide the admin the option to set this via the admin interface. How do I set the CURRENCIES variable in settings.py to the constance.config.CURRENCIES value?

I get ```django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.``` when I try 
```
from constance import config
CURRENCIES = config.CURRENCIES
```

Thanks for your help!

### System configuration

* Django version: 3.0
* Python version: 3.7.4

**Comment by SebCorbin** [comment]
I don't think this is possible, you are running into a chicken-egg problem. You could maybe bind the settings on `config_updated` signal from constance, but I'm not even sure this would work.
