### ISSUE TITLE
 error when i run a server "python manage.py runserver"

### ISSUE THREAD

**Issue by MxondisiNsimbini** [jazzband/django-constance#380]
### Describe the problem
i get an error when i attempt to run the server through a virtualenv   and have tried searching can't find the solution... can i get help please ?
Tell us about the problem you're having
this is what i get :

 **python : Watching for file changes with StatReloader
At line:1 char:1
+ python manage.py runserver
+ ~~~~~~~~~~~~~~~~~~~~~~~ ~~~
    + CategoryInfo          : NotSpecified: (Watching for fi...th StatReloader:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError**
 

### System configuration

* Django version: 3 .0.3
* Python version: 3.8.0

**Comment by Mogost** [comment]
The description of the problem is not enough.
Most likely the problem is not related to django-constance.

**Comment by sheero69** [comment]
i'm facing the same problem sir. 
![image](https://user-images.githubusercontent.com/53946987/88226802-43025180-cc8a-11ea-809f-b14af6d3bd4f.png)
if you got the solution pls help me with it.

**Comment by AjithKerala** [comment]
hey u solve this
