### ISSUE TITLE
how to use postgress with Constance?

### ISSUE THREAD

**Issue by ReemaAH** [jazzband/django-constance#381]
My DB in the project is a Postgress DB
and I need to store the configuration values from Constance in the same Postgress DB
Is that possible with Constance? or I should keep it in a separate DB with Redis?

Django version: 2.2.3
Python 3.7.0

**Comment by camilonova** [comment]
You can use the database backend https://github.com/jazzband/django-constance/blob/master/docs/backends.rst#database
