### ISSUE TITLE
Wrong "is modified" in admin for multi line strings

### ISSUE THREAD

**Issue by Mogost** [jazzband/django-constance#396]
My default value for variable looks like 'Some\n\nText'
After this variable is init, saved and desirialized that looks like 'Some\r\n\r\nText'
For user in admin that looks strange.
Problem line is:
https://github.com/jazzband/django-constance/blob/731514c52fe1e669f6210a8a860bff7846c6f707/constance/admin.py#L208
How about use that approach to compare strings?
```
 'modified': localize(value).splitlines() != localize(default).splitlines()
```

**Comment by camilonova** [comment]
I don't see any problem. There will be some unexpected behavior making that change?

**Comment by Mogost** [comment]
After adding a new variable:
![image](https://user-images.githubusercontent.com/721963/82824086-54f58d00-9eb1-11ea-876a-b011586fa818.png)

Change another value on admin page and click save button on bottom.
![image](https://user-images.githubusercontent.com/721963/82824273-b584ca00-9eb1-11ea-9642-d12e03620477.png)
I did not change the value. Visually, it is absolutely the same for me.
I still can not understand at what point `\n` modified into `\r\n`.  But just changing the flag for designating this line as not modified seems pretty safe to me.

**Comment by Mogost** [comment]
This value come from cleaned_data here
https://github.com/jazzband/django-constance/blob/731514c52fe1e669f6210a8a860bff7846c6f707/constance/admin.py#L147
debugger screen (I have django-constance version 2.4.0 but also on the master branch the same bug):
![image](https://user-images.githubusercontent.com/721963/82826535-00a0dc00-9eb6-11ea-82d0-3ab4e0ff0c6f.png)
