### ISSUE TITLE
Constance upload path

### ISSUE THREAD

**Issue by ghost** [jazzband/django-constance#398]
### Describe the problem

I want to set upload path to constance images and files. How can I do it?

### System configuration

* Django version: 2.2
* Python version: 3.6

**Comment by sudokillpid** [comment]
@ghost Did you manage to find a solution?

**Comment by sudokillpid** [comment]
I too would like to know if this is possible? I'm quite the django noob so I'm not sure how to approach this.

**Comment by BigglesZX** [comment]
It doesn't appear to be possible at the moment, as the library is hardcoded to save the file in the root of the default storage:

https://github.com/jazzband/django-constance/blob/5de44eafb16ef2d0dceea88da295387ccb17230d/constance/admin.py#L141-L144

I'll see if I can manage to create a pull request to add this as a setting.
