### ISSUE TITLE
Hide certain fields from the Django admin interface

### ISSUE THREAD

**Issue by Ricardomol** [jazzband/django-constance#400]
### Describe the problem

I'm using the Django Admin to expose some of the values used by Constance. However, there are a few sensible ones that I would prefer to keep completely hidden from the user interface (not even shown using a password field)

Is this possible?

**Comment by camilonova** [comment]
No

**Comment by noormaniyar** [comment]
class PostCodesAdmin(admin.ModelAdmin):
  exclude = ('pcname',)  #This exclude function will do which u want!
  list_display = ('id', 'gisid', 'title', )
