### ISSUE TITLE
Reset to default does not work with ImageField

### ISSUE THREAD

**Issue by Rotzbua** [jazzband/django-constance#404]
### Describe the problem

I tried the example with ImageField. Default value works. Uploading a new image also works. But if I click the link `Reset to default` nothing happen.

Reseting to default image is not possible.

### Steps to reproduce

Just use the example: 
https://github.com/jazzband/django-constance/blob/2.6.0/docs/index.rst

```python
CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {}]
}

CONSTANCE_CONFIG = {
    'LOGO_IMAGE': ('default.png', 'Company logo', 'image_field'),
}
```

### Tested with browser

Firefox and Chrome current stable. Same result with both.

### Possible source of the issue

Seems to be an issue with a javascript. Browsers show a error message in the console:

Firefox:
```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
```

Chrome:
```
jquery.js:8496 Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```

Source of the issue seems `constance.js` line 23.

### System configuration

* Django version: 3.0.7
* Python version: 3.8.2
* django-constance version: 2.6

Thanks for your great library!

**Comment by andrei-gypaetus** [comment]
Check this post. [https://stackoverflow.com/a/1696891/11910394](https://stackoverflow.com/a/1696891/11910394)

**Comment by Rotzbua** [comment]
> Check this post. https://stackoverflow.com/a/1696891/11910394

For better documentation I post the text from the link

```
The only way to set the value of a file input is by the user to select a file.

This is done for security reasons. Otherwise you would be able to create a JavaScript that automatically uploads a specific file from the client's computer.
```

This is the reason why the javascript on client side throws an error. But it is not impossible at all, because the default file is already on the django server.

If I understand the mechanism correctly, constance currently resets the value on client side by javascript. The javascript just sets the input field to the default value and then submit.

For file or image upload fields this is not possible for security reasons. So the solution is not to modify the upload field and create an alternative field which trigger a reset to default on the server.

**Comment by andrei-gypaetus** [comment]
Thank you, @Rotzbua ! 

IMO, this could be done by adding a specific constance url in order to be triggered from the client.  After the reset to default action is triggered, the reference could be updated on the interface as well.

This feature shouldn't be a difficult one.
