### ISSUE TITLE
Issues with django-picklefield dependency version

### ISSUE THREAD

**Issue by Janekk** [jazzband/django-constance#405]
### Describe the problem

Getting following error:

```
converters = {2: ([<bound method PickledObjectField.from_db_value of <picklefield.fields.PickledObjectField: value>>], Col(constance_config, database.Constance.value))}
    def apply_converters(self, row, converters):
        row = list(row)
        for pos, (convs, expression) in converters.items():
            value = row[pos]
            for converter in convs:
>               value = converter(value, expression, self.connection, self.query.context)
E               TypeError: from_db_value() takes 4 positional arguments but 5 were given
```

Looks like you don't specify the version of `django-picklefield` dependency in your requirements and django-picklefield 3.0 has just been released.

### System configuration

* Django version: 1.11.29
* Python version: 3.6.5

**Comment by Mogost** [comment]
Hi @Janekk. Looks like that is not constance problem. 
`django-picklefield` drop support for django 1.11. https://github.com/gintas/django-picklefield#changes-in-version-300
