### ISSUE TITLE
django-picklefield update breaks backwards incompatibility on version 2.5

### ISSUE THREAD

**Issue by ashleybartlett** [jazzband/django-constance#406]
### Describe the problem

Recent 3.0 patch to django-picklefield has caused a backwards compatibility error on django 1.11 when using django-constance 2.5. I can see that setup.py does not have this dependency versioned.

I added a manual requirement of django-picklefield==2.1.1 and this resolved our issues. 

### Steps to reproduce

Install django==1.11, django-constance==2.5[database] and use it. 

### System configuration

* Django version: 1.11
* Python version: 3.6
* Django-Constance version: 2.5[database]

**Comment by Mogost** [comment]
Like in https://github.com/jazzband/django-constance/issues/405
`django-picklefield` drop support for django 1.11, and that is not `django-constance` problem.
Also `django-constance` [drop support for django<2.2 ](https://django-constance.readthedocs.io/en/latest/changes.html#v2-6-0-2020-01-29) in v2.6.0 (2020/01/29).

**Comment by ashleybartlett** [comment]
I'm aware that both packages have dropped support. The issue is that your version that does support django<2.2 no longer actually supports it.

I was hoping for a 2.5.1 patch which specified a versioned dependency in `setup.py`. This is generally best practice. Going forward best practice is to be pinning your transitive dependencies to help prevent this kind of problem.

**Comment by Mogost** [comment]
You may just as well ask the `django-picklefield` to specify its dependence on django.
In any case, django 1.11 has reached the end of life, it is unreasonable to spend energy on its support in any way.
Moreover, you can determine the version of `django-picklefield` yourself in your project.

Also, I don’t know how jazzband relates to the release of such patch releases. So far, all that I have seen is moving strictly forward, without any patch releases for previous versions. cc: @jezdez
