### ISSUE TITLE
Migration problem on multiple databases

### ISSUE THREAD

**Issue by euthygenes** [jazzband/django-constance#414]
### Describe the problem
Constance tries to migrate my all databases and fails except `default` database.  It should work only `default` database. 

== fail message ==
`
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co..`

### Steps to reproduce
you can add a second database for some special models than try to migrate.

### System configuration

* Django version:
2.2.13
* Python version:
3.6
* Django-Constance version
2.7.0

**Comment by WojtekNosal** [comment]
Use `CONSTANCE_DBS` in settings to limit to certain DBs
[link to changelong](https://django-constance.readthedocs.io/en/latest/changes.html?highlight=CONSTANCE_DBS#v2-2-0-2018-03-23)
