### ISSUE TITLE
About LocMemCache database setting

### ISSUE THREAD

**Issue by hassek** [jazzband/django-constance#423]
### Describe the problem

I want to setup the LocMemCache from django as the cache for the database implementation of this project. This avoids the need to setup a cache mechanism outside of the app.

I know it has it's problems, but my approach is to setup a timeout to the local memory cache so we know a key will be updated after X amount of time.

My problem is that the package, instead of discouraging the use, it prohibits using the django local cache implementation, which I think shouldn't be.

### Steps to reproduce

Tell us how to reproduce it.

### System configuration

* Django version: 3.1.1
* Python version: 3.8.5
* Django-Constance version: 2.7.0

**Comment by Mogost** [comment]
It's not the most common way to use it. But nevertheless, if you are willing to implement it, please suggest a pull request.
