### ISSUE TITLE
question: is it possible to override a variable in settings.py with a constance value?

### ISSUE THREAD

**Issue by davidtingsu** [jazzband/django-constance#43]
is it possible to override a variable in settings.py with a constance value?
My use case is that I want to be able to set DEBUG = True or Debug = False in the constance admin panel.
Also I would like to be able to configure MANDRILL_API_KEY from https://github.com/brack3t/Djrill with a constance variable.

I have been unsuccessful in getting this to work, because constance appears to import from settings.py and when I put 'from constance import config' therefore there is a circular import in my settings.py file.

**Comment by Natureshadow** [comment]
Well, the solution could be as simple as creating a new `config_lazy` shim module that, when getting a valud from it, returns something wrapped in `django.util.functional.lazy`.

If I got this to work, would it be considered?

**Comment by Natureshadow** [comment]
Here's how I did it in ALekSIS: https://edugit.org/AlekSIS/AlekSIS/commit/a09481d01250717b8b025a25063f9f9a2dbf0a72

If someone wants to take that code and embed it into django-constance (or another downstream app), fell free to do so. I agree to licence it under any OSI-approved licence.
