### ISSUE TITLE
Is there a way to set per setting permission?

### ISSUE THREAD

**Issue by ilyachch** [jazzband/django-constance#431]
I need to set permissions for several constance settings for different users, e.g:

```
CONSTANCE_CONFIG = OrderedDict([
    ('PARAM_1': ('something1', 'Param 1')),
    ('PARAM_2': ('something2', 'Param 2')),
    ('PARAM_3': ('something3', 'Param 3')),
    ('PARAM_4': ('something4', 'Param 4')),
])
```

I need to make user1 have access to PARAM_1 and PARAM_2, and user2 have access to PARAM_3 and PARAM_4

Both users are not superusers

Is there a way to do it?

**Comment by camilonova** [comment]
There is not a way to do it.
