### ISSUE TITLE
Missing field warning when using collapse in fieldsets

### ISSUE THREAD

**Issue by dkr13** [jazzband/django-constance#434]
### Describe the problem

When starting the Django server, constance is warning about missing fields, when using collapsed fieldsets: https://django-constance.readthedocs.io/en/latest/#fieldsets-collapsing

### Steps to reproduce

Using the following constance configuration

```python
CONSTANCE_CONFIG = {
    'conf1': ('default1', 'Description1', str),
    'conf2': ('default2', 'Description2', str),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'First Group': {
        'fields': ('conf1', 'conf2'),
        'collapse': False,
    },
}
```

Even `conf1` and `conf2` are included in the fieldset, constance still warns, that they are missing.

### System configuration

* Django version: 3.1.2
* Python version: 3.8.2
* Django-Constance version: 2.7.0

**Comment by johnwquarles** [comment]
@dkr13 I dealt with this as well, finding that it also caused form validation within django-admin to fail.

However, `django-constance` `2.8.0` resolves the issue.
