### ISSUE TITLE
Too many queries

### ISSUE THREAD

**Issue by mavenium** [jazzband/django-constance#443]
### Describe the problem

I use the database backend mode with Memcached. But the number of requests to display the settings is too many.

### Steps to reproduce

1. `context_processors` Setting:
`TEMPLATES = [
    {
        'OPTIONS': {
            'context_processors': [
                'constance.context_processors.config',
            ],
        },
    },
]`

2. CONSTANCE Settings
`CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'`

### System configuration

* Django version: 3.1
* Python version: 3.8
* Django-Constance version: 2.8.0

**Comment by Mogost** [comment]
Is this problem still relevant today?

**Comment by camilonova** [comment]
That doesn't seem to be the case. I'm closing this.
