### ISSUE TITLE
Slows down website

### ISSUE THREAD

**Issue by elishae621** [jazzband/django-constance#450]
Constance has a nice admin touch and making configurations in the settings.py is ideal for site settings but its lazy config seems to cause more harm than good. Using constance I was making 22 queries in 14s to just load the home page while optimizing as much as I knew how to. Using a model, I have only 4 queries in 4 seconds (I know, its still large).

If there was a way to get all the values I need from constance in one query and cache it, I believe performance would be greatly improved.

**Comment by Mogost** [comment]
Using redis as a backend should make loading faster. 
https://django-constance.readthedocs.io/en/latest/backends.html#redis
