### ISSUE TITLE
Questions: Is there a way to move settings like TIME_ZONE to constance

### ISSUE THREAD

**Issue by acschristoph** [jazzband/django-constance#453]
Hi, first constance is great, I would ask is there a way to load settings like TIME_ZONE or LANGUAGE_CODE
from constance.

If I try to load the config in settings.py of course there is an error that apps arent loaded yet.

Is there e post mechanisem or so that I can use ?
Thanks

**Comment by camilonova** [comment]
I think there is no way to do that using constance
