### ISSUE TITLE
Missing migration 0003_alter_constance_id

### ISSUE THREAD

**Issue by bt** [jazzband/django-constance#454]
### Describe the problem

Whenever I run `migrate`, I receive the following message:

```
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

When I run the `makemigrations`, it tries to create a migration to `Alter field id on constance`. Is this normal?

### System configuration

* Django version: 3.2.8
* Python version: 3.9.7
* Django-Constance version: 2.8.0

**Comment by bt** [comment]
Just as an addition, when I run it, the generated file contains the following operation:

```
    operations = [
        migrations.AlterField(
            model_name='constance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

**Comment by bt** [comment]
Oh, it might actually be due to the fact I set `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` in my settings, hopefully someone can confirm for me 😁

**Comment by syurchenko** [comment]
Yes, it is because of it.

**Comment by merwok** [comment]
I think this should stay open: constance should define default_auto_field = AutoField in its AppConfig to avoid depending on the project default.
