### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Amanda-Wakefield** [jazzband/django-constance#459]
Hello!

Is it possible to change the value of a setting defined via Constance through an app? I would like to have a periodic task change one of my settings based on different scenarios but I don't see anything indicating it is possible or not possible in the docs. 

Thanks in advance!

**Comment by Mogost** [comment]
@Amanda-Wakefield please try somthing like that

```python
from constance import config

config.KEY = value
```

**Comment by Amanda-Wakefield** [comment]
@Mogost Thank you for your quick reply! I can change the value of my variable within a task but that change doesn't get the global value updated. Is there a way to call something like a save function? Here is the task I am testing with (removed all code just to see if I can get the constance setting changed).

```
@periodic_task(
    run_every=(crontab(minute="*/1")), name="verify_token", ignore_result=True
)
def verify_token():
        config.ACCEPTING_JOBS = "no"
```

**Comment by syurchenko** [comment]
```
from constance.management.commands.constance import _set_constance_value
_set_constance_value(key, value)
```
