### ISSUE TITLE
Some document titles are missing

### ISSUE THREAD

**Issue by amirali** [jazzband/django-constance#463]
Hello!

I had an issue with Django tests. some of them were failing because it has some problem with django_content_type and by adding a higher verbosity for showing test logs, I find out this package has a problem with it. so read it and find a `CONSTANCE_DBS` settings variable that hasn't been mentioned anywhere in the official document besides some changelogs page. (and I know I just bypass it and doesn't actually fix the problem, but it works for me just fine)

I think it's good to mention this somewhere so it can have a better explanation for the use cases it has.

**Comment by camilonova** [comment]
fixed in https://github.com/jazzband/django-constance/pull/462
