### ISSUE TITLE
The changes does not take effect immediately

### ISSUE THREAD

**Issue by MrLiuhhh** [jazzband/django-constance#465]
### Describe the problem

I changed some configs in django admin platform.But the changes do not take effect immediately, only when I restart the program it work.
The backend is `constance.backends.database.DatabaseBackend`

### Steps to reproduce

Is there any missing configuration？

### System configuration

* Django version:3.2
* Python version:3.9
* Django-Constance version:2.8.0

**Comment by syurchenko** [comment]
Show minimum reproducible test case. I consider you have some bug in code
