### ISSUE TITLE
Is it time to new version ?

### ISSUE THREAD

**Issue by horpto** [jazzband/django-constance#468]
Last version was released over the year ago.

**Comment by camilonova** [comment]
I'll be working on a release soon

**Comment by horpto** [comment]
@camilonova hey, thanks for release of `django-constance==2.9.0` but pypi has only stable 2.8.0 version

**Comment by camilonova** [comment]
I had some trouble releasing the package. I'm waiting for some help https://github.com/orgs/jazzband/teams/django-constance/discussions/1

**Comment by pirods** [comment]
> I had some trouble releasing the package. I'm waiting for some help https://github.com/orgs/jazzband/teams/django-constance/discussions/1

Check out my PR. I managed to build on my fork :)
