### ISSUE TITLE
Question about In Memory Backend with Apache/Gunicorn/uWSGI Processes

### ISSUE THREAD

**Issue by mikelane** [jazzband/django-constance#484]
### Question

If I use an in-memory backend, will the settings propagate to each of the processes when our server is running on Gunicorn or the like?

**Comment by syurchenko** [comment]
no
https://django-constance.readthedocs.io/en/latest/backends.html#caching

> The cache feature won’t work with a cache backend that is incompatible with cross-process caching like the local memory cache backend included in Django because correct cache invalidation can’t be guaranteed.
