### ISSUE TITLE
edc_utils

### ISSUE THREAD

**Issue by sanglisandeep** [jazzband/django-constance#485]
### Describe the problem
![image](https://user-images.githubusercontent.com/41040240/177195191-da18483f-1f38-478f-ad8e-44c494d007b8.png)

Tell us about the problem you're having.
 when i installed Django-audit-fields i am facing this issue that no module named edc_utils as shown in the screen shot 
### Steps to reproduce

Tell us how to reproduce it.
can anyone please help me to solve this?
### System configuration

* Django version:4
* Python version:3.10
* Django-Constance version:

**Comment by sanglisandeep** [comment]
Can any one help me to solve this issue please?

**Comment by syurchenko** [comment]
This problem is not connected to django-constance
