### ISSUE TITLE
Redis backend too many open files

### ISSUE THREAD

**Issue by mikelane** [jazzband/django-constance#490]
### Describe the problem

We have implemented django constance with a redis backend and a 60 local cache. When there is a large amount of traffic, our service becomes unstable, our latency spikes, and we get a ton of logs which say "too many open files." We have isolated the django-constance change as the only change we are deploying when we do this.

Could this issue possibly be related to this: https://stackoverflow.com/a/25283155/3858494?

### Steps to reproduce

Enable django-constance with a Redis backend and a 60 second local cache. Subject the service to a heavy load.

### System configuration

I don't want to reveal this in a public forum.

* Django version: 
* Python version:
* Django-Constance version:

**Comment by horpto** [comment]
Hi, do you use RedisBackend or CachedRedisBackend? do you use something like gevent ?

**Comment by mikelane** [comment]
We used the CachingRedisBackend. We do not use gevent.

**Comment by horpto** [comment]
Well, great somebody except me uses caching. All calls to redis in CachingRedisBackend are occured under the lock so redis client should have only one connection. As `constance` object is singleton to all threads so something wrong maybe with redis-py client internals.

**Comment by sergei-iurchenko** [comment]
show your code please
