### ISSUE TITLE
Repeating queries when constance is installed

### ISSUE THREAD

**Issue by ericswpark** [jazzband/django-constance#504]
### Describe the problem

Sentry is reporting that constance is performing a n + 1 query whenever the main page of my website loads. Strangely the main page does not use any configuration values from constance (as far as I can tell).

### Repeating query

```
SELECT "constance_config"."id", "constance_config"."key", "constance_config"."value" FROM "constance_config" WHERE "constance_config"."key" = %s LIMIT 21
```

<img width="779" alt="N+1 Query SELECT constance_config id, constance_config key, constance_config value FROM constance_config WHERE c" src="https://user-images.githubusercontent.com/13326074/203558076-0cc54b41-fd61-4bdd-937d-5a3464ee494a.png">

### System configuration

* Django version: 4.1.3
* Python version: CPython 3.10.6
* Django-Constance version: [database] 2.9.1

**Comment by sergei-iurchenko** [comment]
Use can use django-debug-toolbar to find the source of the query

**Comment by ericswpark** [comment]
Apparently the main page uses some configuration values which I forgot about, which was revealed with `django-debug-toolbar` (thanks @sergei-iurchenko !) I've decided to leave them as the page is cached so it's not such a performance concern.
