### ISSUE TITLE
Partitioning settings per role?

### ISSUE THREAD

**Issue by chrisspen** [jazzband/django-constance#508]
I think this is more of a feature request, but is there any recommended approach for structuring settings or making them conditional based on environment or role?

Say you have a Constance setting for an "api host" that should be set to X for your production environment. But for your staging environment, it should be set to Y.

Ideally, to simplify application code, you'd want to define it under one Constance variable like "API_HOST", but define two different values, each used based on which environment flag is set. Then, if you put a snapshot of your production database onto your qa/test/staging database, it will automatically use the correct setting even though it's the same data.

Based on the docs, I'm assuming nothing like this is currently supported?

**Comment by sergei-iurchenko** [comment]
Hello, there is no such feature in constance.

How I see different approaches to store project settings:
1) Store settings in code or env vars. Env vars are defined on server. Settings are changed by developers or admins.Settings are static.
2) Store settings in database (like constance). They can be changed by developers, admin, managers, staff and so on. Settings are dynamic.

So your request is to store some static settings in dynamic approach. Env vars solve this problem. I do not see the reason for this feature.

**Comment by chrisspen** [comment]
For anyone who's interested, I was able to implement this on top of Constance pretty easily by storing role-specific values in a pipe-delimited list in standard Constance value, and then subclassing `constance.base.Config` and overriding `__getattr__()` to split and return the correct value based on the current role defined in the env.
