### ISSUE TITLE
Setting image_field value with CLI (Question)

### ISSUE THREAD

**Issue by ShirinovAdil** [jazzband/django-constance#511]
HI!
I have a setting of an image_field type specified as in docs, is it somehow possible to set a value for it using the management command? I'm trying to make a new management command based on `_set_constance_value` but not sure what format should the image be and if it's possible at all.

* Django version: 3.2
* Python version: 3.8
* Django-Constance version: latest

**Comment by sergei-iurchenko** [comment]
ImageField is TextField. So you can set image path as cli param.

**Comment by islam-kamel** [comment]
> I run `constance set HERO_IMAGE 'path/to/file/'` and get this error `CommandError: No file was submitted. Check the encoding type on the form. `
> 
> My guess is it actually requires encoded image in some format since it works like Django forms

Can you attach your config for  constance in a settings.py file ?

**Comment by ShirinovAdil** [comment]
> > I run `constance set HERO_IMAGE 'path/to/file/'` and get this error `CommandError: No file was submitted. Check the encoding type on the form. `
> > My guess is it actually requires encoded image in some format since it works like Django forms
> 
> Can you attach your config for constance in a settings.py file ?

```
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DBS = "default"
CONSTANCE_SUPERUSER_ONLY = False
CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {'required': False}]
}
CONSTANCE_CONFIG = {
    'POWERED_BY_LOGO': ('', 'description', 'image_field'),
    'HERO_IMAGE': ('', 'description.', 'image_field'),
    'SIDEBAR_LOGO': ('', 'description', 'image_field'),
}
```

**Comment by sergei-iurchenko** [comment]
`constance set `works through django from which requires file to exist in memory

**Comment by ShirinovAdil** [comment]
Ok, that makes sense. All my questions are answered, thanks.
