### ISSUE TITLE
Doc demo error : from constance.forms import ConstanceForm

### ISSUE THREAD

**Issue by lijiachang** [jazzband/django-constance#520]
version：django-constance[redis]==2.9.1

https://django-constance.readthedocs.io/en/latest/
demo is:
```
from constance.admin import ConstanceAdmin, Config
from constance.forms import ConstanceForm
class CustomConfigForm(ConstanceForm):
      def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #... do stuff to make your settings form nice ...

class ConfigAdmin(ConstanceAdmin):
    change_list_form = CustomConfigForm
    change_list_template = 'admin/config/settings.html'

admin.site.unregister([Config])
admin.site.register([Config], ConfigAdmin)
```
from constance.**forms** import ConstanceForm
Should be replaced with
from constance.**admin** import ConstanceForm

**Comment by Mogost** [comment]
It shouldn't.
ConstanceForm is declared in forms not in admin

https://github.com/jazzband/django-constance/blob/8c6552fdaf3c335e4e4c1b831b19b43a6d54c834/constance/forms.py#L76
