### ISSUE TITLE
Create 3.0 release

### ISSUE THREAD

**Issue by sergei-iurchenko** [jazzband/django-constance#523]
Let`s create 3.0 release. There are a lot of changes, refactorings, some of them are incompatible.
I have tested from develop branch in my projects and it works good.
I am ready to assist if new bugs appear
@camilonova

**Comment by camilonova** [comment]
pypi build is not happy about it https://github.com/jazzband/django-constance/actions/runs/5394515587/jobs/9795898856

@sergei-iurchenko can you help?

**Comment by DrMeers** [comment]
Seems to be this issue @camilonova : https://github.com/django/asgiref/issues/393

**Comment by sergei-iurchenko** [comment]
Sorry for delay.
What do you think about removing pypy support? https://github.com/jazzband/django-constance/pull/524
It is actually used only for dj 3.2

**Comment by camilonova** [comment]
What's next?

**Comment by sergei-iurchenko** [comment]
Let's do it)

**Comment by felippem** [comment]
> Let's do it)

Are you working on it?

**Comment by sergei-iurchenko** [comment]
@camilonova do we still have any blockers? 
I could make a release but I don't know how and I suppose I don't have enough permissions.

**Comment by camilonova** [comment]
https://github.com/jazzband/django-constance/commit/bc9707d618d733f209483f665320cc4484eb7d52
