### ISSUE TITLE
Values are not updated from the admin page

### ISSUE THREAD

**Issue by housUnus** [jazzband/django-constance#526]
I'm trying to update values from admin section but they are not updated, I added:

```
CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
```
in setting, and

    'constance',
    'constance.backends.database'

to installed apps but still not working.

ex:

```
CONSTANCE_CONFIG = {
    "SITE_TITLE": ("Title", "Project Name"),
    "EMAIL":("support@title.com", "Main Email"),
    "PHONE":("+212664141133", "Phone Number"),
    "LOCATION":("48 rue Oum Errabia", "Location"),
}
```
    

* Django version: 4.2.3
* Python version: 3.8
* Django-Constance version: 2.9.1

**Comment by Schroedingberg** [comment]
Funny enough, I had the same problem but I was missing `'constance.backends.database'` in my installed apps.
After adding that, saving config data to the DB from admin seems to work for me now.
I'll try to figure out the reason for that and let you know then :)

**Comment by Schroedingberg** [comment]
Starting with the low hanging fruits: Is django-picklefield installed?

**Comment by cristianowa** [comment]
I had the same issue, found the answer [here](https://stackoverflow.com/questions/76050875/django-constance-not-setting-up-database-backend). It's worth to add the  `'constance.backends.database' ` need in the [backends](https://django-constance.readthedocs.io/en/latest/backends.html) documentation ?

**Comment by Mogost** [comment]
I believe this problem is not actual in django-constance==3.1.0
