### ISSUE TITLE
Caching getting multiple values

### ISSUE THREAD

**Issue by aboueleyes** [jazzband/django-constance#527]
### Describe the problem

Currently, you cannot `mget` in Database Backend does not use cache at all. is there are reason for this?
In my case, I have a view that needs multiple values, and I need to utilize the cache.

**Comment by Mogost** [comment]
Isn't this a duplicate of https://github.com/jazzband/django-constance/issues/344 ?

**Comment by camilonova** [comment]
It is a duplicate. I'm closing this.
