### ISSUE TITLE
`override_config` decorator doesn't work for pytest classes

### ISSUE THREAD

**Issue by HosseyNJF** [jazzband/django-constance#529]
### Describe the problem

When using the `constance.test.pytest.override_config` on a test class, pytest simply starts ignoring that test class without any errors.

### Steps to reproduce

Write a test like this:
```python
@override_config(SAMPLE_SETTING=10)
class TestSample:
    def test_sample(self):
        assert True is True
```
And run pytest on the file. It responded like this:
```
collecting ... collected 0 items
```
### System configuration

* Django version: 4.1.9
* Python version: 3.11
* Django-Constance version: 2.9.1

**Comment by pchatzou** [comment]
Looks like importing `constance.test.pytest.override_config` causes a problem, doesn't seem it's meant to be public api. If you import `constance.test.override_config` it works. Thus, there are two options:

```
from constance.test import override_config

@override_config(SAMPLE_SETTING=10)
class TestSample:
    def test_sample(self):
        assert True is True
```

Would give you `Exception: Only subclasses of Django SimpleTestCase can be decorated with override_config` (which is also in line with django's `override_settings` behaviour when decorating classes, see [override_settings source](https://github.com/django/django/blob/main/django/test/utils.py#L535)

Alternatively:

```
from constance import config
from constance.test import override_config

@override_config(STRING_VALUE="foo")
def test_sample():
    assert config.STRING_VALUE == "bar"
```

Gives `AssertionError: assert 'foo' == 'bar'`
