### ISSUE TITLE
All config variables are shown to user when server raise 500 and DEBUG=True

### ISSUE THREAD

**Issue by MrArabboy** [jazzband/django-constance#532]
When DEBUG=True and server raise 500 , all config variables and their values are shown to user. How to fix that?

**Comment by camilonova** [comment]
I guess you can set DEBUG to False. The objective of DEBUG is to show the variables and values so you can debug them.

**Comment by MrArabboy** [comment]
> I guess you can set DEBUG to False. The objective of DEBUG is to show the variables and values so you can debug them.

I need config variables mustn't be shown to other users at any time and any case even when DEBUG=True
Is it possible
