### ISSUE TITLE
Ajax Load/Save?

### ISSUE THREAD

**Issue by chrisspen** [jazzband/django-constance#533]
This is more of a question and/or feature request.

I have an application with a fairly large number of Constance variables. So large that it takes the default Constance variable edit page almost a minute to save, even if only a single variable was changed.

Is there any way to change this page so that, instead of listing all variables, there's a simple search field that lets you type in the name of the setting, retrieve the partial form field for that setting, and then let you edit and save that single field?

**Comment by sergei-iurchenko** [comment]
django-constance admin page is usual form like other model forms in django admin.
It is possible to make your own view and to change constance values by one.
