### ISSUE TITLE
Allow modifying defaults

### ISSUE THREAD

**Issue by robin-blanchard** [jazzband/django-constance#535]
### Describe the problem

I didn't find in the docs what to expect when the default value is changed for some key while the value was not modified before change. I did find two distinct behaviours, based on whether or not the value has been modified or read in the past. 

#### First case: Key has not been modified or read

Let's add a new entry to the constance config:
```python
CONSTANCE_CONFIG = {
    'SOME_PARAMETER': ("old default", 'Test key', str),
}
```
![image](https://github.com/jazzband/django-constance/assets/28874798/6f2af82e-c264-4e7e-bb9f-e0bc9a857eeb)

Now, modify the configuration with a new default value:
 ```python
CONSTANCE_CONFIG = {
    'SOME_PARAMETER': ("new default", 'Test key', str),
}
```
![image](https://github.com/jazzband/django-constance/assets/28874798/ed1eaf2e-b10f-41dd-b212-d30f5aa804a6)

Conclusion, `SOME_PARAMETER` has been set to the new default value, as it was not modified before.

Checking what is going on on the database side seems relevant in this issue:
```
# SELECT * FROM constance_constance;
 id | key | value 
----+-----+-------
(0 rows)
```

#### Second case: Read key before modifying default value

Start with a similar configuration:
```python
CONSTANCE_CONFIG = {
    'SECOND_PARAMETER': ("old default", 'Test key', str),
}
```

Now, read it from the console:
```
# python manage.py constance get SECOND_PARAMETER
old default
```

Let's check the database now:
```
# SELECT * FROM constance_constance;
 id |       key        |            value             
----+------------------+------------------------------
  7 | SECOND_PARAMETER | gAJYCwAAAG9sZCBkZWZhdWx0cQAu
(1 row)
```
Reading the key made it write to the database

Let's try to change the default value with `new default`:
![image](https://github.com/jazzband/django-constance/assets/28874798/741f2ab9-906c-40a1-823a-318907b68ef6)

Conclusion: `SECOND_PARAMETER` kept the old default value while it was never modified.

#### Third case: Modify and reset value

Again, let's start with a similar configuration:
```python
CONSTANCE_CONFIG = {
    'THIRD_PARAMETER': ("old default", 'Test key', str),
}
```
![image](https://github.com/jazzband/django-constance/assets/28874798/32796aec-11ba-4087-a7d6-64337601375d)

From the Admin page, or the console, set it to any other value
![image](https://github.com/jazzband/django-constance/assets/28874798/ab7fe279-8d15-4fdf-ae19-962f58d2118f)
On the database side, the value is inscribed to it at this point

And use 'Reset to default'
![image](https://github.com/jazzband/django-constance/assets/28874798/13811e31-fc8b-42d5-b5e2-dcf2470e194c)

Now, as in the second case, change the configuration to modify the default value.
```python
CONSTANCE_CONFIG = {
    'THIRD_PARAMETER': ("new default", 'Test key', str),
}
```
![image](https://github.com/jazzband/django-constance/assets/28874798/84757622-afe2-4a36-88b2-bf480a659487)

Conclusion, resetting it to the default value doesn't make it act as if it has never been modified.

#### Conclusion

I do like the idea of unmodified values "following" the changes of default values, as in the first case. But I guess the current `django-constance` version doesn't feature it. 
- Is there any reason for the lack of behaviour consistency as it is right now ?
- Would it be possible to have unmodified variables auto setting themselves to new default values ? It could also be configured with some `CONSTANCE_XXX` setting
- 

### System configuration

* Django version: 3.2.19
* Python version: 3.9.12
* Django-Constance version: 3.1.0

**Comment by robin-blanchard** [comment]
This behavior comes from this line https://github.com/jazzband/django-constance/blob/master/constance/base.py#L22

**Comment by robin-blanchard** [comment]
So I did a bit of digging.

#### What is happening when the constance isn't set inside the database ?

Getting a new constance resulted in:
- Receiving the default value
- Having it written to the database.

This comes from this line: https://github.com/jazzband/django-constance/blob/master/constance/base.py#L22

#### How to handle the cases in the issue

Since the behaviour I was looking for is "Whenever a constance is set to the default value, I would like it to change when I change the corresponding default value", here's what I did:
```python
from constance.backends.database import DatabaseBackend
from constance import settings, signals, config

from django.db import (
    OperationalError,
    ProgrammingError
)

class CustomDatabaseBackend(DatabaseBackend):

    def set(self, key, value):
        if key not in settings.CONFIG:
            raise AttributeError(key)

        default_value = settings.CONFIG[key][0]

        if value != default_value:
            return super().set(key, value)

        queryset = self._model._default_manager.all()
        # Set _for_write attribute as get_or_create method does
        # https://github.com/django/django/blob/2.2.11/django/db/models/query.py#L536
        queryset._for_write = True

        try:
            constance = queryset.get(key=key)
        except (OperationalError, ProgrammingError):
            # database is not created, noop
            return
        except self._model.DoesNotExist:
            # Key doesn't exist, then do nothing
            return

        old_value = constance.value

        # Constance should be modified to default value -> delete it
        constance.delete(using=queryset.db)

        if self._cache:
            self._cache.set(key, value)

        signals.config_updated.send(
            sender=config, key=key, old_value=old_value, new_value=value
        )
```

**Comment by Mogost** [comment]
@robin-blanchard you are 100% correct. 
I am unsure, but this behavior might be added directly in django-constance. I'd consider a pull request with such a change. Perhaps it contains some additional constraints, but I don't see them at first glance.
