### ISSUE TITLE
Include support for updating multiple fields in management command

### ISSUE THREAD

**Issue by RichardForshaw** [jazzband/django-constance#539]
### Describe the problem

We have a system which needs different configs at different times (e.g. weekday/weekend). Rather than implement multiple fields in Constance to support these different contexts, it would be convenient to have a scheduled task which changes the necessary fields at certain times. Then from a maintenance perspective, we won't need to implement multiple fields for a given behaviour; instead we can maintain a config and just update it when we need to.

In order to do this, it would be good to support updating a list of fields in the management command, rather than just one.

### Steps to reproduce

No reproduction.

### System configuration

Feature request for all configurations.

**Comment by Mogost** [comment]
To do this you can always create a custom command. 
Also, you can propose your realisation as a PR that the community will discuss.
