### ISSUE TITLE
Upgrading from 2.8 to 3.1, existing migrations create a NodeNotFound or InconsistentMigrationHistory error

### ISSUE THREAD

**Issue by easherma-truth** [jazzband/django-constance#541]
### Describe the problem

Hi there, we have an existing app that has migrations we've written that referenced migrations that have now moved in constance and I'm not sure of the guidance of how to handle this properly. 

I've tried updating our migration to refer to the new migrations. That causes an InconsistentMigrationHistory , for example: 
```
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration common.0002_populate_constance_config_values is applied before its dependency constance.0002_migrate_from_old_table on database 'default'. 
```

Unapplying this migration seems less than ideal, I don't want us to lose the values we've already populated. Ideally I'd write a new migration that makes sure to copy all the existing config over (assuming I'd only need to do that if `0002_migrate_from_old_table` dosen't do that). 

If I _don't_ modify our existing migration, I get this error:
```
django.db.migrations.exceptions.NodeNotFoundError: Migration common.0002_populate_constance_config_values dependencies reference nonexistent parent node ('database', '0002_auto_20190129_2304')
```

So I'm wondering what the expected upgrade path is for existing apps that require zero-downtime migrations and no loss of config data?
### Steps to reproduce

1. Have a django project using django-constance < 3.0 with migrations that reference the previous 'database' app migrations
1. Upgrade the dependency and try to run migrations or deploy said app
### System configuration

* Django version: upgrading to 4.2 from 3.2
* Python version: 2.8
* Django-Constance version: Anything above 2.8

**Comment by easherma-truth** [comment]
Another related complication of the new migration is that it drops the old table. This can conflict with zero-downtime migrations, since its possible older code may try to run against the new schema before it is available.

**Comment by sergei-iurchenko** [comment]
Hello, you can fix your historical migrations with:
replace ('database', '0002_auto_20190129_2304') to ('constance', '0002_migrate_from_old_table')

**Comment by Mogost** [comment]
I think @sergei-iurchenko answered the question
