### ISSUE TITLE
collapse.js deleted in django 5.1

### ISSUE THREAD

**Issue by Mogost** [jazzband/django-constance#542]
This script was deleted in Django 5.1 

https://github.com/jazzband/django-constance/blob/cb8ae3985480986a045263778c57fa377767da41/constance/templates/admin/constance/change_list.html#L18

refs: 
https://github.com/django/django/pull/17910
https://github.com/django/django/commit/7857507c7fc43350701700d4215a37baea7655f0
https://code.djangoproject.com/ticket/35189

**Comment by camilonova** [comment]
It will be a matter of only removing that line?

**Comment by Mogost** [comment]
> It will be a matter of only removing that line?

I think so. But we need to take into account backward compatibility with older versions of Django.
