### ISSUE TITLE
bug(docs): build fails

### ISSUE THREAD

**Issue by Rotzbua** [jazzband/django-constance#550]
### Describe the problem

Documentation build fails.

### Reference

> Migrate your project to .readthedocs.yaml configuration file v2

> Monday, September 25, 2023: Fully remove support for building documentation without configuration file v2.

https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by Mogost** [comment]
@Rotzbua Feel free to open an issue in the help repo https://github.com/jazzband/help
