### ISSUE TITLE
JSONDecodeError after upgrading from v3 to v4

### ISSUE THREAD

**Issue by 3ng7n33r** [jazzband/django-constance#591]
### Describe the problem

After upgrading python from 3.10 to 3.12 and django-constance from 3 to 4, the pickled values stored in the database cause 
`"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"` 
during startup.
I do not know how to reset the values as I can start neither the application nor the shell. I tried truncating the constance database table with no success.

### Steps to reproduce

Install django-constance < 4.0
Put values in database
Upgrade django constance to >= 4.0
Start Django

### System configuration

* Django version: 5.0.3
* Python version: 3.12.7
* Django-Constance version: 4.1.2

**Comment by 3ng7n33r** [comment]
Closing this issue but I'll document what happened.
I have been using constance variables in a function that runs during django startup. I had not anticipated the JSONDecodeError so there has been no exception handling for it. As it runs during startup, the migration to convert the pickled values to JSON values could not be applied.
I just added an exception for the error in my function, the migration has been correctly applied and everything is running smooth now. Nothing else to be done here.

**Comment by apollodatasolutions** [comment]
The same JSONDecodeError happened to us, we had some Constance config directives in urls.py and it prevented the Django migration from running, so we temporarily replaced them with hardcoded strings to migrate and then went back to the prior settings.

I googled this but didn't find it (found it manually looking for GitHub issues in the Constance project), so just posting this again to help Google find this answer for Django:

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
