### ISSUE TITLE
Constance doesn't support config values of the type <class 'dict'>

### ISSUE THREAD

**Issue by morrah** [jazzband/django-constance#594]
### Describe the problem

> Constance doesn't support config values of the type <class 'dict'>. Please fix the value of 'MY_VAR'

Error message comes from [forms.py](https://github.com/jazzband/django-constance/blob/d4b41234dac1f254b7a59b98ba870344715388c9/constance/forms.py#L39), `FIELDS` dictionary lacks of new collection-types.

### Steps to reproduce

```
CONSTANCE_CONFIG = {
    'MY_VAR': ({'test': 432}, 'my test var', dict),
}
```

### System configuration

* Django version: 4.1.2
* Python version: 3.11.0rc1
* Django-Constance version: 4.1.2

**Comment by mohammadhasanzadeh** [comment]
Hi, any solution for solving this issue?

**Comment by Mogost** [comment]
You should configure form output for dict as you want. Example from test

https://github.com/jazzband/django-constance/blob/d4b41234dac1f254b7a59b98ba870344715388c9/tests/settings.py#L74-L85

https://github.com/jazzband/django-constance/blob/d4b41234dac1f254b7a59b98ba870344715388c9/tests/settings.py#L55
